// sensor_msgs/msg/NavSatStatus.idl
// Canonical IDL definition for sensor_msgs::msg::NavSatStatus

module sensor_msgs {
  module msg {
    struct NavSatStatus {
      octet status;
      unsigned short service;
    };
  };
};
