// Copyright (c) 2026 Computer Vision Center (CVC) at the Universitat Autonoma
// de Barcelona (UAB).
//
// This work is licensed under the terms of the MIT license.
// For a copy, see <https://opensource.org/licenses/MIT>.

#pragma once

#include "LidarDescription.generated.h"

USTRUCT()
struct CARLA_API FLidarDescription
{
  GENERATED_BODY()

  /// Number of lasers.
  UPROPERTY(EditAnywhere)
  uint32 Channels = 32u;

  /// Measure distance in centimeters.
  UPROPERTY(EditAnywhere)
  float Range = 1000.0f;

  /// Points generated by all lasers per second.
  UPROPERTY(EditAnywhere)
  uint32 PointsPerSecond = 56000u;

  /// Lidar rotation frequency.
  UPROPERTY(EditAnywhere)
  float RotationFrequency = 10.0f;

  /// Upper laser angle, counts from horizontal, positive values means above
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float UpperFovLimit = 10.0f;

  /// Lower laser angle, counts from horizontal, negative values means under
  /// horizontal line.
  UPROPERTY(EditAnywhere)
  float LowerFovLimit = -30.0f;
  
  /// Horizontal field of view
  UPROPERTY(EditAnywhere)
  float HorizontalFov = 360.0f;

  /// Attenuation Rate in the atmosphere in m^-1.
  UPROPERTY(EditAnywhere)
  float AtmospAttenRate = 0.004f;

  /// Random seed for the noise/dropoff used by this sensor.
  UPROPERTY(EditAnywhere)
  int RandomSeed = 0;

  /// General drop off rate.
  UPROPERTY(EditAnywhere)
  float DropOffGenRate = 0.45f;

  /// General drop off rate.
  UPROPERTY(EditAnywhere)
  float DropOffIntensityLimit = 0.8f;

  /// General drop off rate.
  UPROPERTY(EditAnywhere)
  float DropOffAtZeroIntensity = 0.4f;

  /// Wether to show debug points of laser hits in simulator.
  UPROPERTY(EditAnywhere)
  bool ShowDebugPoints = false;

  UPROPERTY(EditAnywhere)
  float NoiseStdDev = 0.0f;

  /// Per-channel vertical angles (degrees, sensor frame).
  /// If non-empty, overrides uniform distribution from UpperFovLimit/LowerFovLimit.
  /// Length determines effective channel count for RGL ray generation.
  TArray<float> VerticalAngles;

  /// Per-channel horizontal angle offsets (degrees).
  /// Applied as azimuth offset for each channel. Empty = all zeros.
  TArray<float> HorizontalAngleOffsets;

  /// Per-channel ring IDs.
  /// If non-empty, overrides sequential (0, 1, 2, ...) assignment.
  TArray<int32> RingIds;

  /// Minimum range in centimeters (default 0).
  UPROPERTY(EditAnywhere)
  float MinRange = 0.0f;

  /// Per-channel periodic range pattern (meters, NOT centimeters).
  /// Array size = Channels × RangePatternPeriod.
  /// Index: channel * RangePatternPeriod + (horizontalStep % RangePatternPeriod)
  /// Empty = use uniform MinRange/Range for all rays.
  TArray<float> PerChannelMinRanges;
  TArray<float> PerChannelMaxRanges;

  /// Range pattern period. 0 = unused (uniform range).
  /// 2 = alternating (e.g. AT128E2X near/far field).
  int32 RangePatternPeriod = 0;

  /// Per-channel horizontal step offset (degrees).
  /// Added to each ray's horizontal angle to enable half-resolution shift
  /// for specific channels (e.g. QT128C2X Bank C/D, Pandar128E4X high-res).
  /// Empty = no shift.
  TArray<float> HorizontalStepOffsets;

  /// Ray mask: azimuth FOV sections (whitelist).
  /// Format: "start,end;start,end;..." (degrees, 0-360, max 5 sections)
  /// Rays outside all sections are masked. Empty = no azimuth mask.
  FString RayMaskAzimuth;

  /// Ray mask: disabled ring IDs (blacklist).
  /// Format: "ring1,ring2,ring3,..." (integers)
  /// Rays with matching ring_id are masked. Empty = no ring mask.
  FString RayMaskRings;

  /// Ray mask: rectangular regions (blacklist).
  /// Format: "az_start,az_end,el_start,el_end;..." (degrees)
  /// azimuth: 0-360, elevation: -90 to 90. Rays inside any rectangle are masked.
  FString RayMaskRects;

  /// Ray mask: per-channel raw mask (1=enabled, 0=masked).
  /// Expanded to per-ray by repeating for each horizontal step.
  TArray<int8> RayMaskRaw;

  /// Noise model: angular noise type ("ray" or "hitpoint"). Empty = no angular noise.
  FString NoiseAngularType;

  /// Noise model: angular noise mean (degrees).
  float NoiseAngularMean = 0.0f;

  /// Noise model: angular noise standard deviation (degrees).
  float NoiseAngularStdDev = 0.0f;

  /// Noise model: distance noise mean (meters).
  float NoiseDistanceMean = 0.0f;

  /// Noise model: distance noise standard deviation base (meters).
  float NoiseDistanceStdDevBase = 0.0f;

  /// Noise model: distance noise standard deviation rise per meter (m/m).
  float NoiseDistanceStdDevRise = 0.0f;

  /// Noise model: angular noise rotation axis ("X", "Y", or "Z").
  FString NoiseAngularAxis;
};
