// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Control.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Control.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define autoware_control_msgs_msg_Longitudinal_max_cdr_typesize 30ULL;
#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_control_msgs_msg_Control_max_cdr_typesize 74ULL;
#define autoware_control_msgs_msg_Lateral_max_cdr_typesize 25ULL;
#define autoware_control_msgs_msg_Longitudinal_max_key_cdr_typesize 0ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define autoware_control_msgs_msg_Control_max_key_cdr_typesize 0ULL;
#define autoware_control_msgs_msg_Lateral_max_key_cdr_typesize 0ULL;

autoware_control_msgs::msg::Control::Control()
{
    // builtin_interfaces::msg::Time m_stamp

    // builtin_interfaces::msg::Time m_control_time

    // autoware_control_msgs::msg::Lateral m_lateral

    // autoware_control_msgs::msg::Longitudinal m_longitudinal


}

autoware_control_msgs::msg::Control::~Control()
{




}

autoware_control_msgs::msg::Control::Control(
        const Control& x)
{
    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_lateral = x.m_lateral;
    m_longitudinal = x.m_longitudinal;
}

autoware_control_msgs::msg::Control::Control(
        Control&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_lateral = std::move(x.m_lateral);
    m_longitudinal = std::move(x.m_longitudinal);
}

autoware_control_msgs::msg::Control& autoware_control_msgs::msg::Control::operator =(
        const Control& x)
{

    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_lateral = x.m_lateral;
    m_longitudinal = x.m_longitudinal;

    return *this;
}

autoware_control_msgs::msg::Control& autoware_control_msgs::msg::Control::operator =(
        Control&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_lateral = std::move(x.m_lateral);
    m_longitudinal = std::move(x.m_longitudinal);

    return *this;
}

bool autoware_control_msgs::msg::Control::operator ==(
        const Control& x) const
{

    return (m_stamp == x.m_stamp && m_control_time == x.m_control_time && m_lateral == x.m_lateral && m_longitudinal == x.m_longitudinal);
}

bool autoware_control_msgs::msg::Control::operator !=(
        const Control& x) const
{
    return !(*this == x);
}

size_t autoware_control_msgs::msg::Control::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Control_max_cdr_typesize;
}

size_t autoware_control_msgs::msg::Control::getCdrSerializedSize(
        const autoware_control_msgs::msg::Control& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.control_time(), current_alignment);
    current_alignment += autoware_control_msgs::msg::Lateral::getCdrSerializedSize(data.lateral(), current_alignment);
    current_alignment += autoware_control_msgs::msg::Longitudinal::getCdrSerializedSize(data.longitudinal(), current_alignment);

    return current_alignment - initial_alignment;
}

void autoware_control_msgs::msg::Control::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_control_time;
    scdr << m_lateral;
    scdr << m_longitudinal;

}

void autoware_control_msgs::msg::Control::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_control_time;
    dcdr >> m_lateral;
    dcdr >> m_longitudinal;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_control_msgs::msg::Control::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_control_msgs::msg::Control::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Control::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Control::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function copies the value in member control_time
 * @param _control_time New value to be copied in member control_time
 */
void autoware_control_msgs::msg::Control::control_time(
        const builtin_interfaces::msg::Time& _control_time)
{
    m_control_time = _control_time;
}

/*!
 * @brief This function moves the value in member control_time
 * @param _control_time New value to be moved in member control_time
 */
void autoware_control_msgs::msg::Control::control_time(
        builtin_interfaces::msg::Time&& _control_time)
{
    m_control_time = std::move(_control_time);
}

/*!
 * @brief This function returns a constant reference to member control_time
 * @return Constant reference to member control_time
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Control::control_time() const
{
    return m_control_time;
}

/*!
 * @brief This function returns a reference to member control_time
 * @return Reference to member control_time
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Control::control_time()
{
    return m_control_time;
}
/*!
 * @brief This function copies the value in member lateral
 * @param _lateral New value to be copied in member lateral
 */
void autoware_control_msgs::msg::Control::lateral(
        const autoware_control_msgs::msg::Lateral& _lateral)
{
    m_lateral = _lateral;
}

/*!
 * @brief This function moves the value in member lateral
 * @param _lateral New value to be moved in member lateral
 */
void autoware_control_msgs::msg::Control::lateral(
        autoware_control_msgs::msg::Lateral&& _lateral)
{
    m_lateral = std::move(_lateral);
}

/*!
 * @brief This function returns a constant reference to member lateral
 * @return Constant reference to member lateral
 */
const autoware_control_msgs::msg::Lateral& autoware_control_msgs::msg::Control::lateral() const
{
    return m_lateral;
}

/*!
 * @brief This function returns a reference to member lateral
 * @return Reference to member lateral
 */
autoware_control_msgs::msg::Lateral& autoware_control_msgs::msg::Control::lateral()
{
    return m_lateral;
}
/*!
 * @brief This function copies the value in member longitudinal
 * @param _longitudinal New value to be copied in member longitudinal
 */
void autoware_control_msgs::msg::Control::longitudinal(
        const autoware_control_msgs::msg::Longitudinal& _longitudinal)
{
    m_longitudinal = _longitudinal;
}

/*!
 * @brief This function moves the value in member longitudinal
 * @param _longitudinal New value to be moved in member longitudinal
 */
void autoware_control_msgs::msg::Control::longitudinal(
        autoware_control_msgs::msg::Longitudinal&& _longitudinal)
{
    m_longitudinal = std::move(_longitudinal);
}

/*!
 * @brief This function returns a constant reference to member longitudinal
 * @return Constant reference to member longitudinal
 */
const autoware_control_msgs::msg::Longitudinal& autoware_control_msgs::msg::Control::longitudinal() const
{
    return m_longitudinal;
}

/*!
 * @brief This function returns a reference to member longitudinal
 * @return Reference to member longitudinal
 */
autoware_control_msgs::msg::Longitudinal& autoware_control_msgs::msg::Control::longitudinal()
{
    return m_longitudinal;
}


size_t autoware_control_msgs::msg::Control::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Control_max_key_cdr_typesize;
}

bool autoware_control_msgs::msg::Control::isKeyDefined()
{
    return false;
}

void autoware_control_msgs::msg::Control::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



