// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Control.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_AUTOWARE_CONTROL_MSGS_MSG_CONTROL_H_
#define _FAST_DDS_GENERATED_AUTOWARE_CONTROL_MSGS_MSG_CONTROL_H_

#include "Time.h"
#include "Longitudinal.h"
#include "Lateral.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CONTROL_SOURCE)
#define CONTROL_DllAPI __declspec( dllexport )
#else
#define CONTROL_DllAPI __declspec( dllimport )
#endif // CONTROL_SOURCE
#else
#define CONTROL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CONTROL_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace autoware_control_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure Control defined by the user in the IDL file.
         * @ingroup Control
         */
        class Control
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Control();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Control();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object autoware_control_msgs::msg::Control that will be copied.
             */
            eProsima_user_DllExport Control(
                    const Control& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object autoware_control_msgs::msg::Control that will be copied.
             */
            eProsima_user_DllExport Control(
                    Control&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object autoware_control_msgs::msg::Control that will be copied.
             */
            eProsima_user_DllExport Control& operator =(
                    const Control& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object autoware_control_msgs::msg::Control that will be copied.
             */
            eProsima_user_DllExport Control& operator =(
                    Control&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x autoware_control_msgs::msg::Control object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Control& x) const;

            /*!
             * @brief Comparison operator.
             * @param x autoware_control_msgs::msg::Control object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Control& x) const;

            /*!
             * @brief This function copies the value in member stamp
             * @param _stamp New value to be copied in member stamp
             */
            eProsima_user_DllExport void stamp(
                    const builtin_interfaces::msg::Time& _stamp);

            /*!
             * @brief This function moves the value in member stamp
             * @param _stamp New value to be moved in member stamp
             */
            eProsima_user_DllExport void stamp(
                    builtin_interfaces::msg::Time&& _stamp);

            /*!
             * @brief This function returns a constant reference to member stamp
             * @return Constant reference to member stamp
             */
            eProsima_user_DllExport const builtin_interfaces::msg::Time& stamp() const;

            /*!
             * @brief This function returns a reference to member stamp
             * @return Reference to member stamp
             */
            eProsima_user_DllExport builtin_interfaces::msg::Time& stamp();
            /*!
             * @brief This function copies the value in member control_time
             * @param _control_time New value to be copied in member control_time
             */
            eProsima_user_DllExport void control_time(
                    const builtin_interfaces::msg::Time& _control_time);

            /*!
             * @brief This function moves the value in member control_time
             * @param _control_time New value to be moved in member control_time
             */
            eProsima_user_DllExport void control_time(
                    builtin_interfaces::msg::Time&& _control_time);

            /*!
             * @brief This function returns a constant reference to member control_time
             * @return Constant reference to member control_time
             */
            eProsima_user_DllExport const builtin_interfaces::msg::Time& control_time() const;

            /*!
             * @brief This function returns a reference to member control_time
             * @return Reference to member control_time
             */
            eProsima_user_DllExport builtin_interfaces::msg::Time& control_time();
            /*!
             * @brief This function copies the value in member lateral
             * @param _lateral New value to be copied in member lateral
             */
            eProsima_user_DllExport void lateral(
                    const autoware_control_msgs::msg::Lateral& _lateral);

            /*!
             * @brief This function moves the value in member lateral
             * @param _lateral New value to be moved in member lateral
             */
            eProsima_user_DllExport void lateral(
                    autoware_control_msgs::msg::Lateral&& _lateral);

            /*!
             * @brief This function returns a constant reference to member lateral
             * @return Constant reference to member lateral
             */
            eProsima_user_DllExport const autoware_control_msgs::msg::Lateral& lateral() const;

            /*!
             * @brief This function returns a reference to member lateral
             * @return Reference to member lateral
             */
            eProsima_user_DllExport autoware_control_msgs::msg::Lateral& lateral();
            /*!
             * @brief This function copies the value in member longitudinal
             * @param _longitudinal New value to be copied in member longitudinal
             */
            eProsima_user_DllExport void longitudinal(
                    const autoware_control_msgs::msg::Longitudinal& _longitudinal);

            /*!
             * @brief This function moves the value in member longitudinal
             * @param _longitudinal New value to be moved in member longitudinal
             */
            eProsima_user_DllExport void longitudinal(
                    autoware_control_msgs::msg::Longitudinal&& _longitudinal);

            /*!
             * @brief This function returns a constant reference to member longitudinal
             * @return Constant reference to member longitudinal
             */
            eProsima_user_DllExport const autoware_control_msgs::msg::Longitudinal& longitudinal() const;

            /*!
             * @brief This function returns a reference to member longitudinal
             * @return Reference to member longitudinal
             */
            eProsima_user_DllExport autoware_control_msgs::msg::Longitudinal& longitudinal();

            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const autoware_control_msgs::msg::Control& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            builtin_interfaces::msg::Time m_stamp;
            builtin_interfaces::msg::Time m_control_time;
            autoware_control_msgs::msg::Lateral m_lateral;
            autoware_control_msgs::msg::Longitudinal m_longitudinal;

        };
    } // namespace msg
} // namespace autoware_control_msgs

#endif // _FAST_DDS_GENERATED_AUTOWARE_CONTROL_MSGS_MSG_CONTROL_H_

