// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Longitudinal.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Longitudinal.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define autoware_control_msgs_msg_Longitudinal_max_cdr_typesize 30ULL;
#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_control_msgs_msg_Longitudinal_max_key_cdr_typesize 0ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;

autoware_control_msgs::msg::Longitudinal::Longitudinal()
{
    // builtin_interfaces::msg::Time m_stamp

    // builtin_interfaces::msg::Time m_control_time

    // float m_velocity
    m_velocity = 0.0;
    // float m_acceleration
    m_acceleration = 0.0;
    // float m_jerk
    m_jerk = 0.0;
    // boolean m_is_defined_acceleration
    m_is_defined_acceleration = false;
    // boolean m_is_defined_jerk
    m_is_defined_jerk = false;

}

autoware_control_msgs::msg::Longitudinal::~Longitudinal()
{







}

autoware_control_msgs::msg::Longitudinal::Longitudinal(
        const Longitudinal& x)
{
    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_velocity = x.m_velocity;
    m_acceleration = x.m_acceleration;
    m_jerk = x.m_jerk;
    m_is_defined_acceleration = x.m_is_defined_acceleration;
    m_is_defined_jerk = x.m_is_defined_jerk;
}

autoware_control_msgs::msg::Longitudinal::Longitudinal(
        Longitudinal&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_velocity = x.m_velocity;
    m_acceleration = x.m_acceleration;
    m_jerk = x.m_jerk;
    m_is_defined_acceleration = x.m_is_defined_acceleration;
    m_is_defined_jerk = x.m_is_defined_jerk;
}

autoware_control_msgs::msg::Longitudinal& autoware_control_msgs::msg::Longitudinal::operator =(
        const Longitudinal& x)
{

    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_velocity = x.m_velocity;
    m_acceleration = x.m_acceleration;
    m_jerk = x.m_jerk;
    m_is_defined_acceleration = x.m_is_defined_acceleration;
    m_is_defined_jerk = x.m_is_defined_jerk;

    return *this;
}

autoware_control_msgs::msg::Longitudinal& autoware_control_msgs::msg::Longitudinal::operator =(
        Longitudinal&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_velocity = x.m_velocity;
    m_acceleration = x.m_acceleration;
    m_jerk = x.m_jerk;
    m_is_defined_acceleration = x.m_is_defined_acceleration;
    m_is_defined_jerk = x.m_is_defined_jerk;

    return *this;
}

bool autoware_control_msgs::msg::Longitudinal::operator ==(
        const Longitudinal& x) const
{

    return (m_stamp == x.m_stamp && m_control_time == x.m_control_time && m_velocity == x.m_velocity && m_acceleration == x.m_acceleration && m_jerk == x.m_jerk && m_is_defined_acceleration == x.m_is_defined_acceleration && m_is_defined_jerk == x.m_is_defined_jerk);
}

bool autoware_control_msgs::msg::Longitudinal::operator !=(
        const Longitudinal& x) const
{
    return !(*this == x);
}

size_t autoware_control_msgs::msg::Longitudinal::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Longitudinal_max_cdr_typesize;
}

size_t autoware_control_msgs::msg::Longitudinal::getCdrSerializedSize(
        const autoware_control_msgs::msg::Longitudinal& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.control_time(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void autoware_control_msgs::msg::Longitudinal::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_control_time;
    scdr << m_velocity;
    scdr << m_acceleration;
    scdr << m_jerk;
    scdr << m_is_defined_acceleration;
    scdr << m_is_defined_jerk;

}

void autoware_control_msgs::msg::Longitudinal::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_control_time;
    dcdr >> m_velocity;
    dcdr >> m_acceleration;
    dcdr >> m_jerk;
    dcdr >> m_is_defined_acceleration;
    dcdr >> m_is_defined_jerk;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_control_msgs::msg::Longitudinal::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_control_msgs::msg::Longitudinal::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Longitudinal::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Longitudinal::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function copies the value in member control_time
 * @param _control_time New value to be copied in member control_time
 */
void autoware_control_msgs::msg::Longitudinal::control_time(
        const builtin_interfaces::msg::Time& _control_time)
{
    m_control_time = _control_time;
}

/*!
 * @brief This function moves the value in member control_time
 * @param _control_time New value to be moved in member control_time
 */
void autoware_control_msgs::msg::Longitudinal::control_time(
        builtin_interfaces::msg::Time&& _control_time)
{
    m_control_time = std::move(_control_time);
}

/*!
 * @brief This function returns a constant reference to member control_time
 * @return Constant reference to member control_time
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Longitudinal::control_time() const
{
    return m_control_time;
}

/*!
 * @brief This function returns a reference to member control_time
 * @return Reference to member control_time
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Longitudinal::control_time()
{
    return m_control_time;
}
/*!
 * @brief This function sets a value in member velocity
 * @param _velocity New value for member velocity
 */
void autoware_control_msgs::msg::Longitudinal::velocity(
        float _velocity)
{
    m_velocity = _velocity;
}

/*!
 * @brief This function returns the value of member velocity
 * @return Value of member velocity
 */
float autoware_control_msgs::msg::Longitudinal::velocity() const
{
    return m_velocity;
}

/*!
 * @brief This function returns a reference to member velocity
 * @return Reference to member velocity
 */
float& autoware_control_msgs::msg::Longitudinal::velocity()
{
    return m_velocity;
}

/*!
 * @brief This function sets a value in member acceleration
 * @param _acceleration New value for member acceleration
 */
void autoware_control_msgs::msg::Longitudinal::acceleration(
        float _acceleration)
{
    m_acceleration = _acceleration;
}

/*!
 * @brief This function returns the value of member acceleration
 * @return Value of member acceleration
 */
float autoware_control_msgs::msg::Longitudinal::acceleration() const
{
    return m_acceleration;
}

/*!
 * @brief This function returns a reference to member acceleration
 * @return Reference to member acceleration
 */
float& autoware_control_msgs::msg::Longitudinal::acceleration()
{
    return m_acceleration;
}

/*!
 * @brief This function sets a value in member jerk
 * @param _jerk New value for member jerk
 */
void autoware_control_msgs::msg::Longitudinal::jerk(
        float _jerk)
{
    m_jerk = _jerk;
}

/*!
 * @brief This function returns the value of member jerk
 * @return Value of member jerk
 */
float autoware_control_msgs::msg::Longitudinal::jerk() const
{
    return m_jerk;
}

/*!
 * @brief This function returns a reference to member jerk
 * @return Reference to member jerk
 */
float& autoware_control_msgs::msg::Longitudinal::jerk()
{
    return m_jerk;
}

/*!
 * @brief This function sets a value in member is_defined_acceleration
 * @param _is_defined_acceleration New value for member is_defined_acceleration
 */
void autoware_control_msgs::msg::Longitudinal::is_defined_acceleration(
        bool _is_defined_acceleration)
{
    m_is_defined_acceleration = _is_defined_acceleration;
}

/*!
 * @brief This function returns the value of member is_defined_acceleration
 * @return Value of member is_defined_acceleration
 */
bool autoware_control_msgs::msg::Longitudinal::is_defined_acceleration() const
{
    return m_is_defined_acceleration;
}

/*!
 * @brief This function returns a reference to member is_defined_acceleration
 * @return Reference to member is_defined_acceleration
 */
bool& autoware_control_msgs::msg::Longitudinal::is_defined_acceleration()
{
    return m_is_defined_acceleration;
}

/*!
 * @brief This function sets a value in member is_defined_jerk
 * @param _is_defined_jerk New value for member is_defined_jerk
 */
void autoware_control_msgs::msg::Longitudinal::is_defined_jerk(
        bool _is_defined_jerk)
{
    m_is_defined_jerk = _is_defined_jerk;
}

/*!
 * @brief This function returns the value of member is_defined_jerk
 * @return Value of member is_defined_jerk
 */
bool autoware_control_msgs::msg::Longitudinal::is_defined_jerk() const
{
    return m_is_defined_jerk;
}

/*!
 * @brief This function returns a reference to member is_defined_jerk
 * @return Reference to member is_defined_jerk
 */
bool& autoware_control_msgs::msg::Longitudinal::is_defined_jerk()
{
    return m_is_defined_jerk;
}



size_t autoware_control_msgs::msg::Longitudinal::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Longitudinal_max_key_cdr_typesize;
}

bool autoware_control_msgs::msg::Longitudinal::isKeyDefined()
{
    return false;
}

void autoware_control_msgs::msg::Longitudinal::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



