// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TurnIndicatorsCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TurnIndicatorsCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_vehicle_msgs_msg_TurnIndicatorsCommand_max_cdr_typesize 9ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define autoware_vehicle_msgs_msg_TurnIndicatorsCommand_max_key_cdr_typesize 0ULL;






autoware_vehicle_msgs::msg::TurnIndicatorsCommand::TurnIndicatorsCommand()
{
    // builtin_interfaces::msg::Time m_stamp

    // uint8 m_command
    m_command = 0;

}

autoware_vehicle_msgs::msg::TurnIndicatorsCommand::~TurnIndicatorsCommand()
{


}

autoware_vehicle_msgs::msg::TurnIndicatorsCommand::TurnIndicatorsCommand(
        const TurnIndicatorsCommand& x)
{
    m_stamp = x.m_stamp;
    m_command = x.m_command;
}

autoware_vehicle_msgs::msg::TurnIndicatorsCommand::TurnIndicatorsCommand(
        TurnIndicatorsCommand&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_command = x.m_command;
}

autoware_vehicle_msgs::msg::TurnIndicatorsCommand& autoware_vehicle_msgs::msg::TurnIndicatorsCommand::operator =(
        const TurnIndicatorsCommand& x)
{

    m_stamp = x.m_stamp;
    m_command = x.m_command;

    return *this;
}

autoware_vehicle_msgs::msg::TurnIndicatorsCommand& autoware_vehicle_msgs::msg::TurnIndicatorsCommand::operator =(
        TurnIndicatorsCommand&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_command = x.m_command;

    return *this;
}

bool autoware_vehicle_msgs::msg::TurnIndicatorsCommand::operator ==(
        const TurnIndicatorsCommand& x) const
{

    return (m_stamp == x.m_stamp && m_command == x.m_command);
}

bool autoware_vehicle_msgs::msg::TurnIndicatorsCommand::operator !=(
        const TurnIndicatorsCommand& x) const
{
    return !(*this == x);
}

size_t autoware_vehicle_msgs::msg::TurnIndicatorsCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_TurnIndicatorsCommand_max_cdr_typesize;
}

size_t autoware_vehicle_msgs::msg::TurnIndicatorsCommand::getCdrSerializedSize(
        const autoware_vehicle_msgs::msg::TurnIndicatorsCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_command;

}

void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_command;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::TurnIndicatorsCommand::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::TurnIndicatorsCommand::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function sets a value in member command
 * @param _command New value for member command
 */
void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::command(
        uint8_t _command)
{
    m_command = _command;
}

/*!
 * @brief This function returns the value of member command
 * @return Value of member command
 */
uint8_t autoware_vehicle_msgs::msg::TurnIndicatorsCommand::command() const
{
    return m_command;
}

/*!
 * @brief This function returns a reference to member command
 * @return Reference to member command
 */
uint8_t& autoware_vehicle_msgs::msg::TurnIndicatorsCommand::command()
{
    return m_command;
}



size_t autoware_vehicle_msgs::msg::TurnIndicatorsCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_TurnIndicatorsCommand_max_key_cdr_typesize;
}

bool autoware_vehicle_msgs::msg::TurnIndicatorsCommand::isKeyDefined()
{
    return false;
}

void autoware_vehicle_msgs::msg::TurnIndicatorsCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



