// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VelocityReport.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VelocityReport.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_vehicle_msgs_msg_VelocityReport_max_cdr_typesize 280ULL;
#define std_msgs_msg_Header_max_cdr_typesize 268ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define autoware_vehicle_msgs_msg_VelocityReport_max_key_cdr_typesize 0ULL;
#define std_msgs_msg_Header_max_key_cdr_typesize 0ULL;

autoware_vehicle_msgs::msg::VelocityReport::VelocityReport()
{
    // std_msgs::msg::Header m_header

    // float m_longitudinal_velocity
    m_longitudinal_velocity = 0.0;
    // float m_lateral_velocity
    m_lateral_velocity = 0.0;
    // float m_heading_rate
    m_heading_rate = 0.0;

}

autoware_vehicle_msgs::msg::VelocityReport::~VelocityReport()
{




}

autoware_vehicle_msgs::msg::VelocityReport::VelocityReport(
        const VelocityReport& x)
{
    m_header = x.m_header;
    m_longitudinal_velocity = x.m_longitudinal_velocity;
    m_lateral_velocity = x.m_lateral_velocity;
    m_heading_rate = x.m_heading_rate;
}

autoware_vehicle_msgs::msg::VelocityReport::VelocityReport(
        VelocityReport&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_longitudinal_velocity = x.m_longitudinal_velocity;
    m_lateral_velocity = x.m_lateral_velocity;
    m_heading_rate = x.m_heading_rate;
}

autoware_vehicle_msgs::msg::VelocityReport& autoware_vehicle_msgs::msg::VelocityReport::operator =(
        const VelocityReport& x)
{

    m_header = x.m_header;
    m_longitudinal_velocity = x.m_longitudinal_velocity;
    m_lateral_velocity = x.m_lateral_velocity;
    m_heading_rate = x.m_heading_rate;

    return *this;
}

autoware_vehicle_msgs::msg::VelocityReport& autoware_vehicle_msgs::msg::VelocityReport::operator =(
        VelocityReport&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_longitudinal_velocity = x.m_longitudinal_velocity;
    m_lateral_velocity = x.m_lateral_velocity;
    m_heading_rate = x.m_heading_rate;

    return *this;
}

bool autoware_vehicle_msgs::msg::VelocityReport::operator ==(
        const VelocityReport& x) const
{

    return (m_header == x.m_header && m_longitudinal_velocity == x.m_longitudinal_velocity && m_lateral_velocity == x.m_lateral_velocity && m_heading_rate == x.m_heading_rate);
}

bool autoware_vehicle_msgs::msg::VelocityReport::operator !=(
        const VelocityReport& x) const
{
    return !(*this == x);
}

size_t autoware_vehicle_msgs::msg::VelocityReport::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_VelocityReport_max_cdr_typesize;
}

size_t autoware_vehicle_msgs::msg::VelocityReport::getCdrSerializedSize(
        const autoware_vehicle_msgs::msg::VelocityReport& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += std_msgs::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void autoware_vehicle_msgs::msg::VelocityReport::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_longitudinal_velocity;
    scdr << m_lateral_velocity;
    scdr << m_heading_rate;

}

void autoware_vehicle_msgs::msg::VelocityReport::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_longitudinal_velocity;
    dcdr >> m_lateral_velocity;
    dcdr >> m_heading_rate;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void autoware_vehicle_msgs::msg::VelocityReport::header(
        const std_msgs::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void autoware_vehicle_msgs::msg::VelocityReport::header(
        std_msgs::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::Header& autoware_vehicle_msgs::msg::VelocityReport::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::Header& autoware_vehicle_msgs::msg::VelocityReport::header()
{
    return m_header;
}
/*!
 * @brief This function sets a value in member longitudinal_velocity
 * @param _longitudinal_velocity New value for member longitudinal_velocity
 */
void autoware_vehicle_msgs::msg::VelocityReport::longitudinal_velocity(
        float _longitudinal_velocity)
{
    m_longitudinal_velocity = _longitudinal_velocity;
}

/*!
 * @brief This function returns the value of member longitudinal_velocity
 * @return Value of member longitudinal_velocity
 */
float autoware_vehicle_msgs::msg::VelocityReport::longitudinal_velocity() const
{
    return m_longitudinal_velocity;
}

/*!
 * @brief This function returns a reference to member longitudinal_velocity
 * @return Reference to member longitudinal_velocity
 */
float& autoware_vehicle_msgs::msg::VelocityReport::longitudinal_velocity()
{
    return m_longitudinal_velocity;
}

/*!
 * @brief This function sets a value in member lateral_velocity
 * @param _lateral_velocity New value for member lateral_velocity
 */
void autoware_vehicle_msgs::msg::VelocityReport::lateral_velocity(
        float _lateral_velocity)
{
    m_lateral_velocity = _lateral_velocity;
}

/*!
 * @brief This function returns the value of member lateral_velocity
 * @return Value of member lateral_velocity
 */
float autoware_vehicle_msgs::msg::VelocityReport::lateral_velocity() const
{
    return m_lateral_velocity;
}

/*!
 * @brief This function returns a reference to member lateral_velocity
 * @return Reference to member lateral_velocity
 */
float& autoware_vehicle_msgs::msg::VelocityReport::lateral_velocity()
{
    return m_lateral_velocity;
}

/*!
 * @brief This function sets a value in member heading_rate
 * @param _heading_rate New value for member heading_rate
 */
void autoware_vehicle_msgs::msg::VelocityReport::heading_rate(
        float _heading_rate)
{
    m_heading_rate = _heading_rate;
}

/*!
 * @brief This function returns the value of member heading_rate
 * @return Value of member heading_rate
 */
float autoware_vehicle_msgs::msg::VelocityReport::heading_rate() const
{
    return m_heading_rate;
}

/*!
 * @brief This function returns a reference to member heading_rate
 * @return Reference to member heading_rate
 */
float& autoware_vehicle_msgs::msg::VelocityReport::heading_rate()
{
    return m_heading_rate;
}



size_t autoware_vehicle_msgs::msg::VelocityReport::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_VelocityReport_max_key_cdr_typesize;
}

bool autoware_vehicle_msgs::msg::VelocityReport::isKeyDefined()
{
    return false;
}

void autoware_vehicle_msgs::msg::VelocityReport::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



