/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/CameraInfo.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/sensor_msgs/msg/CameraInfo.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_CAMERAINFO_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_CAMERAINFO_H

#include "Header.h"

#include "RegionOfInterest.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_DOUBLE_DEFINED
#define DDS_SEQUENCE_DOUBLE_DEFINED
typedef struct dds_sequence_double
{
  uint32_t _maximum;
  uint32_t _length;
  double *_buffer;
  bool _release;
} dds_sequence_double;

#define dds_sequence_double__alloc() \
((dds_sequence_double*) dds_alloc (sizeof (dds_sequence_double)));

#define dds_sequence_double_allocbuf(l) \
((double *) dds_alloc ((l) * sizeof (double)))
#endif /* DDS_SEQUENCE_DOUBLE_DEFINED */

typedef struct sensor_msgs_msg_CameraInfo
{
  struct std_msgs_msg_Header header;
  uint32_t height;
  uint32_t width;
  char * distortion_model;
  dds_sequence_double d;
  double k[9];
  double r[9];
  double p[12];
  uint32_t binning_x;
  uint32_t binning_y;
  struct sensor_msgs_msg_RegionOfInterest roi;
} sensor_msgs_msg_CameraInfo;

extern const dds_topic_descriptor_t sensor_msgs_msg_CameraInfo_desc;

#define sensor_msgs_msg_CameraInfo__alloc() \
((sensor_msgs_msg_CameraInfo*) dds_alloc (sizeof (sensor_msgs_msg_CameraInfo)));

#define sensor_msgs_msg_CameraInfo_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_CameraInfo_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_CAMERAINFO_H */
