/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/CarlaEgoVehicleControl.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/carla_msgs/msg/CarlaEgoVehicleControl.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_CARLAEGOVEHICLECONTROL_H
#define DDSC_DDS_CYCLONEDDS_TYPES_CARLAEGOVEHICLECONTROL_H

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct carla_msgs_msg_CarlaEgoVehicleControl
{
  struct std_msgs_msg_Header header;
  float throttle;
  float steer;
  float brake;
  bool hand_brake;
  bool reverse;
  int32_t gear;
  bool manual_gear_shift;
} carla_msgs_msg_CarlaEgoVehicleControl;

extern const dds_topic_descriptor_t carla_msgs_msg_CarlaEgoVehicleControl_desc;

#define carla_msgs_msg_CarlaEgoVehicleControl__alloc() \
((carla_msgs_msg_CarlaEgoVehicleControl*) dds_alloc (sizeof (carla_msgs_msg_CarlaEgoVehicleControl)));

#define carla_msgs_msg_CarlaEgoVehicleControl_free(d,o) \
dds_sample_free ((d), &carla_msgs_msg_CarlaEgoVehicleControl_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_CARLAEGOVEHICLECONTROL_H */
