/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/CarlaCollisionEvent.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/carla_msgs/msg/CarlaCollisionEvent.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_CARLACOLLISIONEVENT_H
#define DDSC_DDS_CYCLONEDDS_TYPES_CARLACOLLISIONEVENT_H

#include "std_msgs/msg/Header.h"

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct carla_msgs_msg_CarlaCollisionEvent
{
  struct std_msgs_msg_Header header;
  uint32_t other_actor_id;
  struct geometry_msgs_msg_Vector3 normal_impulse;
} carla_msgs_msg_CarlaCollisionEvent;

extern const dds_topic_descriptor_t carla_msgs_msg_CarlaCollisionEvent_desc;

#define carla_msgs_msg_CarlaCollisionEvent__alloc() \
((carla_msgs_msg_CarlaCollisionEvent*) dds_alloc (sizeof (carla_msgs_msg_CarlaCollisionEvent)));

#define carla_msgs_msg_CarlaCollisionEvent_free(d,o) \
dds_sample_free ((d), &carla_msgs_msg_CarlaCollisionEvent_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_CARLACOLLISIONEVENT_H */
