/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/CarlaLineInvasion.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/carla_msgs/msg/CarlaLineInvasion.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_CARLALINEINVASION_H
#define DDSC_DDS_CYCLONEDDS_TYPES_CARLALINEINVASION_H

#include "std_msgs/msg/Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_LONG_DEFINED
#define DDS_SEQUENCE_LONG_DEFINED
typedef struct dds_sequence_long
{
  uint32_t _maximum;
  uint32_t _length;
  int32_t *_buffer;
  bool _release;
} dds_sequence_long;

#define dds_sequence_long__alloc() \
((dds_sequence_long*) dds_alloc (sizeof (dds_sequence_long)));

#define dds_sequence_long_allocbuf(l) \
((int32_t *) dds_alloc ((l) * sizeof (int32_t)))
#endif /* DDS_SEQUENCE_LONG_DEFINED */

typedef struct carla_msgs_msg_CarlaLineInvasion
{
  struct std_msgs_msg_Header header;
  dds_sequence_long crossed_lane_markings;
} carla_msgs_msg_CarlaLineInvasion;

extern const dds_topic_descriptor_t carla_msgs_msg_CarlaLineInvasion_desc;

#define carla_msgs_msg_CarlaLineInvasion__alloc() \
((carla_msgs_msg_CarlaLineInvasion*) dds_alloc (sizeof (carla_msgs_msg_CarlaLineInvasion)));

#define carla_msgs_msg_CarlaLineInvasion_free(d,o) \
dds_sample_free ((d), &carla_msgs_msg_CarlaLineInvasion_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_CARLALINEINVASION_H */
