/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Clock.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/rosgraph_msgs/msg/Clock.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_CLOCK_H
#define DDSC_DDS_CYCLONEDDS_TYPES_CLOCK_H

#include "builtin_interfaces/msg/Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct rosgraph_msgs_msg_Clock
{
  struct builtin_interfaces_msg_Time clock;
} rosgraph_msgs_msg_Clock;

extern const dds_topic_descriptor_t rosgraph_msgs_msg_Clock_desc;

#define rosgraph_msgs_msg_Clock__alloc() \
((rosgraph_msgs_msg_Clock*) dds_alloc (sizeof (rosgraph_msgs_msg_Clock)));

#define rosgraph_msgs_msg_Clock_free(d,o) \
dds_sample_free ((d), &rosgraph_msgs_msg_Clock_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_CLOCK_H */
