/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Control.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_control_msgs/msg/Control.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_CONTROL_H
#define DDSC_DDS_CYCLONEDDS_TYPES_CONTROL_H

#include "builtin_interfaces/msg/Time.h"

#include "autoware_control_msgs/msg/Lateral.h"

#include "autoware_control_msgs/msg/Longitudinal.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_control_msgs_msg_Control
{
  struct builtin_interfaces_msg_Time stamp;
  struct builtin_interfaces_msg_Time control_time;
  struct autoware_control_msgs_msg_Lateral lateral;
  struct autoware_control_msgs_msg_Longitudinal longitudinal;
} autoware_control_msgs_msg_Control;

extern const dds_topic_descriptor_t autoware_control_msgs_msg_Control_desc;

#define autoware_control_msgs_msg_Control__alloc() \
((autoware_control_msgs_msg_Control*) dds_alloc (sizeof (autoware_control_msgs_msg_Control)));

#define autoware_control_msgs_msg_Control_free(d,o) \
dds_sample_free ((d), &autoware_control_msgs_msg_Control_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_CONTROL_H */
