/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Float32.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/std_msgs/msg/Float32.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_FLOAT32_H
#define DDSC_DDS_CYCLONEDDS_TYPES_FLOAT32_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_Float32
{
  float data;
} std_msgs_msg_Float32;

extern const dds_topic_descriptor_t std_msgs_msg_Float32_desc;

#define std_msgs_msg_Float32__alloc() \
((std_msgs_msg_Float32*) dds_alloc (sizeof (std_msgs_msg_Float32)));

#define std_msgs_msg_Float32_free(d,o) \
dds_sample_free ((d), &std_msgs_msg_Float32_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_FLOAT32_H */
