/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/Imu.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/sensor_msgs/msg/Imu.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_IMU_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_IMU_H

#include "Header.h"

#include "Quaternion.h"

#include "Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_Imu
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Quaternion orientation;
  double orientation_covariance[9];
  struct geometry_msgs_msg_Vector3 angular_velocity;
  double angular_velocity_covariance[9];
  struct geometry_msgs_msg_Vector3 linear_acceleration;
  double linear_acceleration_covariance[9];
} sensor_msgs_msg_Imu;

extern const dds_topic_descriptor_t sensor_msgs_msg_Imu_desc;

#define sensor_msgs_msg_Imu__alloc() \
((sensor_msgs_msg_Imu*) dds_alloc (sizeof (sensor_msgs_msg_Imu)));

#define sensor_msgs_msg_Imu_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_Imu_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_IMU_H */
