/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Lateral.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_control_msgs/msg/Lateral.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_LATERAL_H
#define DDSC_DDS_CYCLONEDDS_TYPES_LATERAL_H

#include "Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_control_msgs_msg_Lateral
{
  struct builtin_interfaces_msg_Time stamp;
  struct builtin_interfaces_msg_Time control_time;
  float steering_tire_angle;
  float steering_tire_rotation_rate;
  bool is_defined_steering_tire_rotation_rate;
} autoware_control_msgs_msg_Lateral;

extern const dds_topic_descriptor_t autoware_control_msgs_msg_Lateral_desc;

#define autoware_control_msgs_msg_Lateral__alloc() \
((autoware_control_msgs_msg_Lateral*) dds_alloc (sizeof (autoware_control_msgs_msg_Lateral)));

#define autoware_control_msgs_msg_Lateral_free(d,o) \
dds_sample_free ((d), &autoware_control_msgs_msg_Lateral_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_LATERAL_H */
