/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Longitudinal.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_control_msgs/msg/Longitudinal.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_LONGITUDINAL_H
#define DDSC_DDS_CYCLONEDDS_TYPES_LONGITUDINAL_H

#include "builtin_interfaces/msg/Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_control_msgs_msg_Longitudinal
{
  struct builtin_interfaces_msg_Time stamp;
  struct builtin_interfaces_msg_Time control_time;
  float velocity;
  float acceleration;
  float jerk;
  bool is_defined_acceleration;
  bool is_defined_jerk;
} autoware_control_msgs_msg_Longitudinal;

extern const dds_topic_descriptor_t autoware_control_msgs_msg_Longitudinal_desc;

#define autoware_control_msgs_msg_Longitudinal__alloc() \
((autoware_control_msgs_msg_Longitudinal*) dds_alloc (sizeof (autoware_control_msgs_msg_Longitudinal)));

#define autoware_control_msgs_msg_Longitudinal_free(d,o) \
dds_sample_free ((d), &autoware_control_msgs_msg_Longitudinal_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_LONGITUDINAL_H */
