/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/NavSatStatus.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/sensor_msgs/msg/NavSatStatus.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H
#define DDSC_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_NavSatStatus
{
  uint8_t status;
  uint16_t service;
} sensor_msgs_msg_NavSatStatus;

extern const dds_topic_descriptor_t sensor_msgs_msg_NavSatStatus_desc;

#define sensor_msgs_msg_NavSatStatus__alloc() \
((sensor_msgs_msg_NavSatStatus*) dds_alloc (sizeof (sensor_msgs_msg_NavSatStatus)));

#define sensor_msgs_msg_NavSatStatus_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_NavSatStatus_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H */
