/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/NavSatStatus.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/sensor_msgs/msg/NavSatStatus.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_NavSatStatus
{
  uint8_t status;
  uint16_t service;
} sensor_msgs_msg_NavSatStatus;

extern const dds_topic_descriptor_t sensor_msgs_msg_NavSatStatus_desc;

#define sensor_msgs_msg_NavSatStatus__alloc() \
((sensor_msgs_msg_NavSatStatus*) dds_alloc (sizeof (sensor_msgs_msg_NavSatStatus)));

#define sensor_msgs_msg_NavSatStatus_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_NavSatStatus_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_NAVSATSTATUS_H */
