/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/NavSatFix.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/sensor_msgs/msg/NavSatFix.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_NAVSATFIX_H
#define DDSC_DDS_CYCLONEDDS_TYPES_NAVSATFIX_H

#include "std_msgs/msg/Header.h"

#include "sensor_msgs/msg/NavSatStatus.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_NavSatFix
{
  struct std_msgs_msg_Header header;
  struct sensor_msgs_msg_NavSatStatus status;
  double latitude;
  double longitude;
  double altitude;
  double position_covariance[9];
  uint8_t position_covariance_type;
} sensor_msgs_msg_NavSatFix;

extern const dds_topic_descriptor_t sensor_msgs_msg_NavSatFix_desc;

#define sensor_msgs_msg_NavSatFix__alloc() \
((sensor_msgs_msg_NavSatFix*) dds_alloc (sizeof (sensor_msgs_msg_NavSatFix)));

#define sensor_msgs_msg_NavSatFix_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_NavSatFix_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_NAVSATFIX_H */
