/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/Odometry.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/nav_msgs/msg/Odometry.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ODOMETRY_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ODOMETRY_H

#include "Header.h"

#include "PoseWithCovariance.h"

#include "TwistWithCovariance.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct nav_msgs_msg_Odometry
{
  struct std_msgs_msg_Header header;
  char * child_frame_id;
  struct geometry_msgs_msg_PoseWithCovariance pose;
  struct geometry_msgs_msg_TwistWithCovariance twist;
} nav_msgs_msg_Odometry;

extern const dds_topic_descriptor_t nav_msgs_msg_Odometry_desc;

#define nav_msgs_msg_Odometry__alloc() \
((nav_msgs_msg_Odometry*) dds_alloc (sizeof (nav_msgs_msg_Odometry)));

#define nav_msgs_msg_Odometry_free(d,o) \
dds_sample_free ((d), &nav_msgs_msg_Odometry_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_ODOMETRY_H */
