/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/PointField.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/sensor_msgs/msg/PointField.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINTFIELD_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINTFIELD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_PointField
{
  char * name;
  uint32_t offset;
  uint8_t datatype;
  uint32_t count;
} sensor_msgs_msg_PointField;

extern const dds_topic_descriptor_t sensor_msgs_msg_PointField_desc;

#define sensor_msgs_msg_PointField__alloc() \
((sensor_msgs_msg_PointField*) dds_alloc (sizeof (sensor_msgs_msg_PointField)));

#define sensor_msgs_msg_PointField_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_PointField_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINTFIELD_H */
