/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/PointField.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/sensor_msgs/msg/PointField.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_POINTFIELD_H
#define DDSC_DDS_CYCLONEDDS_TYPES_POINTFIELD_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct sensor_msgs_msg_PointField
{
  char * name;
  uint32_t offset;
  uint8_t datatype;
  uint32_t count;
} sensor_msgs_msg_PointField;

extern const dds_topic_descriptor_t sensor_msgs_msg_PointField_desc;

#define sensor_msgs_msg_PointField__alloc() \
((sensor_msgs_msg_PointField*) dds_alloc (sizeof (sensor_msgs_msg_PointField)));

#define sensor_msgs_msg_PointField_free(d,o) \
dds_sample_free ((d), &sensor_msgs_msg_PointField_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_POINTFIELD_H */
