/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/Point32.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Point32.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINT32_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINT32_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Point32
{
  float x;
  float y;
  float z;
} geometry_msgs_msg_Point32;

extern const dds_topic_descriptor_t geometry_msgs_msg_Point32_desc;

#define geometry_msgs_msg_Point32__alloc() \
((geometry_msgs_msg_Point32*) dds_alloc (sizeof (geometry_msgs_msg_Point32)));

#define geometry_msgs_msg_Point32_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Point32_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POINT32_H */
