/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/PoseWithCovarianceStamped.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/PoseWithCovarianceStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H
#define DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H

#include "std_msgs/msg/Header.h"

#include "geometry_msgs/msg/PoseWithCovariance.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseWithCovarianceStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_PoseWithCovariance pose;
} geometry_msgs_msg_PoseWithCovarianceStamped;

extern const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovarianceStamped_desc;

#define geometry_msgs_msg_PoseWithCovarianceStamped__alloc() \
((geometry_msgs_msg_PoseWithCovarianceStamped*) dds_alloc (sizeof (geometry_msgs_msg_PoseWithCovarianceStamped)));

#define geometry_msgs_msg_PoseWithCovarianceStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseWithCovarianceStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H */
