/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Pose.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Pose.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_POSE_H
#define DDSC_DDS_CYCLONEDDS_TYPES_POSE_H

#include "geometry_msgs/msg/Point.h"

#include "geometry_msgs/msg/Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Pose
{
  struct geometry_msgs_msg_Point position;
  struct geometry_msgs_msg_Quaternion orientation;
} geometry_msgs_msg_Pose;

extern const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc;

#define geometry_msgs_msg_Pose__alloc() \
((geometry_msgs_msg_Pose*) dds_alloc (sizeof (geometry_msgs_msg_Pose)));

#define geometry_msgs_msg_Pose_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Pose_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_POSE_H */
