/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/PoseWithCovariance.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/PoseWithCovariance.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCE_H
#define DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCE_H

#include "Pose.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseWithCovariance
{
  struct geometry_msgs_msg_Pose pose;
  double covariance[36];
} geometry_msgs_msg_PoseWithCovariance;

extern const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovariance_desc;

#define geometry_msgs_msg_PoseWithCovariance__alloc() \
((geometry_msgs_msg_PoseWithCovariance*) dds_alloc (sizeof (geometry_msgs_msg_PoseWithCovariance)));

#define geometry_msgs_msg_PoseWithCovariance_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseWithCovariance_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCE_H */
