/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/Pose.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Pose.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSE_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSE_H

#include "Point.h"

#include "Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Pose
{
  struct geometry_msgs_msg_Point position;
  struct geometry_msgs_msg_Quaternion orientation;
} geometry_msgs_msg_Pose;

extern const dds_topic_descriptor_t geometry_msgs_msg_Pose_desc;

#define geometry_msgs_msg_Pose__alloc() \
((geometry_msgs_msg_Pose*) dds_alloc (sizeof (geometry_msgs_msg_Pose)));

#define geometry_msgs_msg_Pose_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Pose_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSE_H */
