/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/PoseWithCovarianceStamped.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/PoseWithCovarianceStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H

#include "Header.h"

#include "PoseWithCovariance.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseWithCovarianceStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_PoseWithCovariance pose;
} geometry_msgs_msg_PoseWithCovarianceStamped;

extern const dds_topic_descriptor_t geometry_msgs_msg_PoseWithCovarianceStamped_desc;

#define geometry_msgs_msg_PoseWithCovarianceStamped__alloc() \
((geometry_msgs_msg_PoseWithCovarianceStamped*) dds_alloc (sizeof (geometry_msgs_msg_PoseWithCovarianceStamped)));

#define geometry_msgs_msg_PoseWithCovarianceStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseWithCovarianceStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSEWITHCOVARIANCESTAMPED_H */
