/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Quaternion.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Quaternion.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_QUATERNION_H
#define DDSC_DDS_CYCLONEDDS_TYPES_QUATERNION_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Quaternion
{
  double x;
  double y;
  double z;
  double w;
} geometry_msgs_msg_Quaternion;

extern const dds_topic_descriptor_t geometry_msgs_msg_Quaternion_desc;

#define geometry_msgs_msg_Quaternion__alloc() \
((geometry_msgs_msg_Quaternion*) dds_alloc (sizeof (geometry_msgs_msg_Quaternion)));

#define geometry_msgs_msg_Quaternion_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Quaternion_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_QUATERNION_H */
