/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/SteeringReport.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_vehicle_msgs/msg/SteeringReport.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_STEERINGREPORT_H
#define DDSC_DDS_CYCLONEDDS_TYPES_STEERINGREPORT_H

#include "builtin_interfaces/msg/Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_vehicle_msgs_msg_SteeringReport
{
  struct builtin_interfaces_msg_Time stamp;
  float steering_tire_angle;
} autoware_vehicle_msgs_msg_SteeringReport;

extern const dds_topic_descriptor_t autoware_vehicle_msgs_msg_SteeringReport_desc;

#define autoware_vehicle_msgs_msg_SteeringReport__alloc() \
((autoware_vehicle_msgs_msg_SteeringReport*) dds_alloc (sizeof (autoware_vehicle_msgs_msg_SteeringReport)));

#define autoware_vehicle_msgs_msg_SteeringReport_free(d,o) \
dds_sample_free ((d), &autoware_vehicle_msgs_msg_SteeringReport_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_STEERINGREPORT_H */
