/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/String.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/std_msgs/msg/String.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_STRING_H
#define DDSC_DDS_CYCLONEDDS_TYPES_STRING_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct std_msgs_msg_String_
{
  char * data;
} std_msgs_msg_String_;

extern const dds_topic_descriptor_t std_msgs_msg_String__desc;

#define std_msgs_msg_String___alloc() \
((std_msgs_msg_String_*) dds_alloc (sizeof (std_msgs_msg_String_)));

#define std_msgs_msg_String__free(d,o) \
dds_sample_free ((d), &std_msgs_msg_String__desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_STRING_H */
