/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/TF2Error.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/tf2_msgs/msg/TF2Error.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TF2ERROR_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TF2ERROR_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct tf2_msgs_msg_TF2Error
{
  uint8_t error;
  char * error_string;
} tf2_msgs_msg_TF2Error;

extern const dds_topic_descriptor_t tf2_msgs_msg_TF2Error_desc;

#define tf2_msgs_msg_TF2Error__alloc() \
((tf2_msgs_msg_TF2Error*) dds_alloc (sizeof (tf2_msgs_msg_TF2Error)));

#define tf2_msgs_msg_TF2Error_free(d,o) \
dds_sample_free ((d), &tf2_msgs_msg_TF2Error_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TF2ERROR_H */
