/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Transform.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Transform.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_TRANSFORM_H
#define DDSC_DDS_CYCLONEDDS_TYPES_TRANSFORM_H

#include "Vector3.h"

#include "Quaternion.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Transform
{
  struct geometry_msgs_msg_Vector3 translation;
  struct geometry_msgs_msg_Quaternion rotation;
} geometry_msgs_msg_Transform;

extern const dds_topic_descriptor_t geometry_msgs_msg_Transform_desc;

#define geometry_msgs_msg_Transform__alloc() \
((geometry_msgs_msg_Transform*) dds_alloc (sizeof (geometry_msgs_msg_Transform)));

#define geometry_msgs_msg_Transform_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Transform_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_TRANSFORM_H */
