/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/TransformStamped.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/TransformStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TRANSFORMSTAMPED_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TRANSFORMSTAMPED_H

#include "Header.h"

#include "Transform.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_TransformStamped
{
  struct std_msgs_msg_Header header;
  char * child_frame_id;
  struct geometry_msgs_msg_Transform transform;
} geometry_msgs_msg_TransformStamped;

extern const dds_topic_descriptor_t geometry_msgs_msg_TransformStamped_desc;

#define geometry_msgs_msg_TransformStamped__alloc() \
((geometry_msgs_msg_TransformStamped*) dds_alloc (sizeof (geometry_msgs_msg_TransformStamped)));

#define geometry_msgs_msg_TransformStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_TransformStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TRANSFORMSTAMPED_H */
