/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/TurnIndicatorsReport.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_vehicle_msgs/msg/TurnIndicatorsReport.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_TURNINDICATORSREPORT_H
#define DDSC_DDS_CYCLONEDDS_TYPES_TURNINDICATORSREPORT_H

#include "Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_vehicle_msgs_msg_TurnIndicatorsReport
{
  struct builtin_interfaces_msg_Time stamp;
  uint8_t report;
} autoware_vehicle_msgs_msg_TurnIndicatorsReport;

extern const dds_topic_descriptor_t autoware_vehicle_msgs_msg_TurnIndicatorsReport_desc;

#define autoware_vehicle_msgs_msg_TurnIndicatorsReport__alloc() \
((autoware_vehicle_msgs_msg_TurnIndicatorsReport*) dds_alloc (sizeof (autoware_vehicle_msgs_msg_TurnIndicatorsReport)));

#define autoware_vehicle_msgs_msg_TurnIndicatorsReport_free(d,o) \
dds_sample_free ((d), &autoware_vehicle_msgs_msg_TurnIndicatorsReport_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_TURNINDICATORSREPORT_H */
