/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/TurnIndicatorsCommand.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_vehicle_msgs/msg/TurnIndicatorsCommand.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TURNINDICATORSCOMMAND_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TURNINDICATORSCOMMAND_H

#include "Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_vehicle_msgs_msg_TurnIndicatorsCommand
{
  struct builtin_interfaces_msg_Time stamp;
  uint8_t command;
} autoware_vehicle_msgs_msg_TurnIndicatorsCommand;

extern const dds_topic_descriptor_t autoware_vehicle_msgs_msg_TurnIndicatorsCommand_desc;

#define autoware_vehicle_msgs_msg_TurnIndicatorsCommand__alloc() \
((autoware_vehicle_msgs_msg_TurnIndicatorsCommand*) dds_alloc (sizeof (autoware_vehicle_msgs_msg_TurnIndicatorsCommand)));

#define autoware_vehicle_msgs_msg_TurnIndicatorsCommand_free(d,o) \
dds_sample_free ((d), &autoware_vehicle_msgs_msg_TurnIndicatorsCommand_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_TURNINDICATORSCOMMAND_H */
