/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/TwistWithCovariance.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/TwistWithCovariance.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_TWISTWITHCOVARIANCE_H
#define DDSC_DDS_CYCLONEDDS_TYPES_TWISTWITHCOVARIANCE_H

#include "geometry_msgs/msg/Twist.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_TwistWithCovariance
{
  struct geometry_msgs_msg_Twist twist;
  double covariance[36];
} geometry_msgs_msg_TwistWithCovariance;

extern const dds_topic_descriptor_t geometry_msgs_msg_TwistWithCovariance_desc;

#define geometry_msgs_msg_TwistWithCovariance__alloc() \
((geometry_msgs_msg_TwistWithCovariance*) dds_alloc (sizeof (geometry_msgs_msg_TwistWithCovariance)));

#define geometry_msgs_msg_TwistWithCovariance_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_TwistWithCovariance_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_TWISTWITHCOVARIANCE_H */
