/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Twist.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Twist.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_TWIST_H
#define DDSC_DDS_CYCLONEDDS_TYPES_TWIST_H

#include "geometry_msgs/msg/Vector3.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Twist
{
  struct geometry_msgs_msg_Vector3 linear;
  struct geometry_msgs_msg_Vector3 angular;
} geometry_msgs_msg_Twist;

extern const dds_topic_descriptor_t geometry_msgs_msg_Twist_desc;

#define geometry_msgs_msg_Twist__alloc() \
((geometry_msgs_msg_Twist*) dds_alloc (sizeof (geometry_msgs_msg_Twist)));

#define geometry_msgs_msg_Twist_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Twist_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_TWIST_H */
