/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: dds/cyclonedds/types/Vector3.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/geometry_msgs/msg/Vector3.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC_DDS_CYCLONEDDS_TYPES_VECTOR3_H
#define DDSC_DDS_CYCLONEDDS_TYPES_VECTOR3_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_Vector3
{
  double x;
  double y;
  double z;
} geometry_msgs_msg_Vector3;

extern const dds_topic_descriptor_t geometry_msgs_msg_Vector3_desc;

#define geometry_msgs_msg_Vector3__alloc() \
((geometry_msgs_msg_Vector3*) dds_alloc (sizeof (geometry_msgs_msg_Vector3)));

#define geometry_msgs_msg_Vector3_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_Vector3_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_DDS_CYCLONEDDS_TYPES_VECTOR3_H */
