/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/VehicleEmergencyStamped.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/tier4_vehicle_msgs/msg/VehicleEmergencyStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VEHICLEEMERGENCYSTAMPED_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VEHICLEEMERGENCYSTAMPED_H

#include "Time.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct tier4_vehicle_msgs_msg_VehicleEmergencyStamped
{
  struct builtin_interfaces_msg_Time stamp;
  bool emergency;
} tier4_vehicle_msgs_msg_VehicleEmergencyStamped;

extern const dds_topic_descriptor_t tier4_vehicle_msgs_msg_VehicleEmergencyStamped_desc;

#define tier4_vehicle_msgs_msg_VehicleEmergencyStamped__alloc() \
((tier4_vehicle_msgs_msg_VehicleEmergencyStamped*) dds_alloc (sizeof (tier4_vehicle_msgs_msg_VehicleEmergencyStamped)));

#define tier4_vehicle_msgs_msg_VehicleEmergencyStamped_free(d,o) \
dds_sample_free ((d), &tier4_vehicle_msgs_msg_VehicleEmergencyStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VEHICLEEMERGENCYSTAMPED_H */
