/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/dds/cyclonedds/types/VelocityReport.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5-dds-abstraction/LibCarla/source/carla/ros2/types/autoware_vehicle_msgs/msg/VelocityReport.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VELOCITYREPORT_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VELOCITYREPORT_H

#include "Header.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct autoware_vehicle_msgs_msg_VelocityReport
{
  struct std_msgs_msg_Header header;
  float longitudinal_velocity;
  float lateral_velocity;
  float heading_rate;
} autoware_vehicle_msgs_msg_VelocityReport;

extern const dds_topic_descriptor_t autoware_vehicle_msgs_msg_VelocityReport_desc;

#define autoware_vehicle_msgs_msg_VelocityReport__alloc() \
((autoware_vehicle_msgs_msg_VelocityReport*) dds_alloc (sizeof (autoware_vehicle_msgs_msg_VelocityReport)));

#define autoware_vehicle_msgs_msg_VelocityReport_free(d,o) \
dds_sample_free ((d), &autoware_vehicle_msgs_msg_VelocityReport_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_DDS_ABSTRACTION_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_VELOCITYREPORT_H */
