// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file ControlModeReport.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "ControlModeReport.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define autoware_vehicle_msgs_msg_ControlModeReport_max_cdr_typesize 9ULL;
#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_vehicle_msgs_msg_ControlModeReport_max_key_cdr_typesize 0ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;









autoware_vehicle_msgs::msg::ControlModeReport::ControlModeReport()
{
    // builtin_interfaces::msg::Time m_stamp

    // uint8 m_mode
    m_mode = 0;

}

autoware_vehicle_msgs::msg::ControlModeReport::~ControlModeReport()
{


}

autoware_vehicle_msgs::msg::ControlModeReport::ControlModeReport(
        const ControlModeReport& x)
{
    m_stamp = x.m_stamp;
    m_mode = x.m_mode;
}

autoware_vehicle_msgs::msg::ControlModeReport::ControlModeReport(
        ControlModeReport&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_mode = x.m_mode;
}

autoware_vehicle_msgs::msg::ControlModeReport& autoware_vehicle_msgs::msg::ControlModeReport::operator =(
        const ControlModeReport& x)
{

    m_stamp = x.m_stamp;
    m_mode = x.m_mode;

    return *this;
}

autoware_vehicle_msgs::msg::ControlModeReport& autoware_vehicle_msgs::msg::ControlModeReport::operator =(
        ControlModeReport&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_mode = x.m_mode;

    return *this;
}

bool autoware_vehicle_msgs::msg::ControlModeReport::operator ==(
        const ControlModeReport& x) const
{

    return (m_stamp == x.m_stamp && m_mode == x.m_mode);
}

bool autoware_vehicle_msgs::msg::ControlModeReport::operator !=(
        const ControlModeReport& x) const
{
    return !(*this == x);
}

size_t autoware_vehicle_msgs::msg::ControlModeReport::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_ControlModeReport_max_cdr_typesize;
}

size_t autoware_vehicle_msgs::msg::ControlModeReport::getCdrSerializedSize(
        const autoware_vehicle_msgs::msg::ControlModeReport& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void autoware_vehicle_msgs::msg::ControlModeReport::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_mode;

}

void autoware_vehicle_msgs::msg::ControlModeReport::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_mode;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_vehicle_msgs::msg::ControlModeReport::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_vehicle_msgs::msg::ControlModeReport::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::ControlModeReport::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::ControlModeReport::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function sets a value in member mode
 * @param _mode New value for member mode
 */
void autoware_vehicle_msgs::msg::ControlModeReport::mode(
        uint8_t _mode)
{
    m_mode = _mode;
}

/*!
 * @brief This function returns the value of member mode
 * @return Value of member mode
 */
uint8_t autoware_vehicle_msgs::msg::ControlModeReport::mode() const
{
    return m_mode;
}

/*!
 * @brief This function returns a reference to member mode
 * @return Reference to member mode
 */
uint8_t& autoware_vehicle_msgs::msg::ControlModeReport::mode()
{
    return m_mode;
}



size_t autoware_vehicle_msgs::msg::ControlModeReport::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_ControlModeReport_max_key_cdr_typesize;
}

bool autoware_vehicle_msgs::msg::ControlModeReport::isKeyDefined()
{
    return false;
}

void autoware_vehicle_msgs::msg::ControlModeReport::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



