// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GearCommand.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_GEARCOMMAND_H_
#define _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_GEARCOMMAND_H_

#include "builtin_interfaces/msg/Time.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(GEARCOMMAND_SOURCE)
#define GEARCOMMAND_DllAPI __declspec( dllexport )
#else
#define GEARCOMMAND_DllAPI __declspec( dllimport )
#endif // GEARCOMMAND_SOURCE
#else
#define GEARCOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define GEARCOMMAND_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace autoware_vehicle_msgs {
    namespace msg {
        namespace GearCommand_Constants {
            const uint8_t NONE = 0;
            const uint8_t NEUTRAL = 1;
            const uint8_t DRIVE = 2;
            const uint8_t DRIVE_2 = 3;
            const uint8_t DRIVE_3 = 4;
            const uint8_t DRIVE_4 = 5;
            const uint8_t DRIVE_5 = 6;
            const uint8_t DRIVE_6 = 7;
            const uint8_t DRIVE_7 = 8;
            const uint8_t DRIVE_8 = 9;
            const uint8_t DRIVE_9 = 10;
            const uint8_t DRIVE_10 = 11;
            const uint8_t DRIVE_11 = 12;
            const uint8_t DRIVE_12 = 13;
            const uint8_t DRIVE_13 = 14;
            const uint8_t DRIVE_14 = 15;
            const uint8_t DRIVE_15 = 16;
            const uint8_t DRIVE_16 = 17;
            const uint8_t DRIVE_17 = 18;
            const uint8_t DRIVE_18 = 19;
            const uint8_t REVERSE = 20;
            const uint8_t REVERSE_2 = 21;
            const uint8_t PARK = 22;
            const uint8_t LOW = 23;
            const uint8_t LOW_2 = 24;
        } // namespace GearCommand_Constants
        /*!
         * @brief This class represents the structure GearCommand defined by the user in the IDL file.
         * @ingroup GearCommand
         */
        class GearCommand
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport GearCommand();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~GearCommand();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object autoware_vehicle_msgs::msg::GearCommand that will be copied.
             */
            eProsima_user_DllExport GearCommand(
                    const GearCommand& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object autoware_vehicle_msgs::msg::GearCommand that will be copied.
             */
            eProsima_user_DllExport GearCommand(
                    GearCommand&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object autoware_vehicle_msgs::msg::GearCommand that will be copied.
             */
            eProsima_user_DllExport GearCommand& operator =(
                    const GearCommand& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object autoware_vehicle_msgs::msg::GearCommand that will be copied.
             */
            eProsima_user_DllExport GearCommand& operator =(
                    GearCommand&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x autoware_vehicle_msgs::msg::GearCommand object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const GearCommand& x) const;

            /*!
             * @brief Comparison operator.
             * @param x autoware_vehicle_msgs::msg::GearCommand object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const GearCommand& x) const;

            /*!
             * @brief This function copies the value in member stamp
             * @param _stamp New value to be copied in member stamp
             */
            eProsima_user_DllExport void stamp(
                    const builtin_interfaces::msg::Time& _stamp);

            /*!
             * @brief This function moves the value in member stamp
             * @param _stamp New value to be moved in member stamp
             */
            eProsima_user_DllExport void stamp(
                    builtin_interfaces::msg::Time&& _stamp);

            /*!
             * @brief This function returns a constant reference to member stamp
             * @return Constant reference to member stamp
             */
            eProsima_user_DllExport const builtin_interfaces::msg::Time& stamp() const;

            /*!
             * @brief This function returns a reference to member stamp
             * @return Reference to member stamp
             */
            eProsima_user_DllExport builtin_interfaces::msg::Time& stamp();
            /*!
             * @brief This function sets a value in member command
             * @param _command New value for member command
             */
            eProsima_user_DllExport void command(
                    uint8_t _command);

            /*!
             * @brief This function returns the value of member command
             * @return Value of member command
             */
            eProsima_user_DllExport uint8_t command() const;

            /*!
             * @brief This function returns a reference to member command
             * @return Reference to member command
             */
            eProsima_user_DllExport uint8_t& command();


            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const autoware_vehicle_msgs::msg::GearCommand& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            builtin_interfaces::msg::Time m_stamp;
            uint8_t m_command;

        };
    } // namespace msg
} // namespace autoware_vehicle_msgs

#endif // _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_GEARCOMMAND_H_

