// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Lateral.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Lateral.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_control_msgs_msg_Lateral_max_cdr_typesize 25ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define autoware_control_msgs_msg_Lateral_max_key_cdr_typesize 0ULL;

autoware_control_msgs::msg::Lateral::Lateral()
{
    // builtin_interfaces::msg::Time m_stamp

    // builtin_interfaces::msg::Time m_control_time

    // float m_steering_tire_angle
    m_steering_tire_angle = 0.0;
    // float m_steering_tire_rotation_rate
    m_steering_tire_rotation_rate = 0.0;
    // boolean m_is_defined_steering_tire_rotation_rate
    m_is_defined_steering_tire_rotation_rate = false;

}

autoware_control_msgs::msg::Lateral::~Lateral()
{





}

autoware_control_msgs::msg::Lateral::Lateral(
        const Lateral& x)
{
    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_steering_tire_angle = x.m_steering_tire_angle;
    m_steering_tire_rotation_rate = x.m_steering_tire_rotation_rate;
    m_is_defined_steering_tire_rotation_rate = x.m_is_defined_steering_tire_rotation_rate;
}

autoware_control_msgs::msg::Lateral::Lateral(
        Lateral&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_steering_tire_angle = x.m_steering_tire_angle;
    m_steering_tire_rotation_rate = x.m_steering_tire_rotation_rate;
    m_is_defined_steering_tire_rotation_rate = x.m_is_defined_steering_tire_rotation_rate;
}

autoware_control_msgs::msg::Lateral& autoware_control_msgs::msg::Lateral::operator =(
        const Lateral& x)
{

    m_stamp = x.m_stamp;
    m_control_time = x.m_control_time;
    m_steering_tire_angle = x.m_steering_tire_angle;
    m_steering_tire_rotation_rate = x.m_steering_tire_rotation_rate;
    m_is_defined_steering_tire_rotation_rate = x.m_is_defined_steering_tire_rotation_rate;

    return *this;
}

autoware_control_msgs::msg::Lateral& autoware_control_msgs::msg::Lateral::operator =(
        Lateral&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_control_time = std::move(x.m_control_time);
    m_steering_tire_angle = x.m_steering_tire_angle;
    m_steering_tire_rotation_rate = x.m_steering_tire_rotation_rate;
    m_is_defined_steering_tire_rotation_rate = x.m_is_defined_steering_tire_rotation_rate;

    return *this;
}

bool autoware_control_msgs::msg::Lateral::operator ==(
        const Lateral& x) const
{

    return (m_stamp == x.m_stamp && m_control_time == x.m_control_time && m_steering_tire_angle == x.m_steering_tire_angle && m_steering_tire_rotation_rate == x.m_steering_tire_rotation_rate && m_is_defined_steering_tire_rotation_rate == x.m_is_defined_steering_tire_rotation_rate);
}

bool autoware_control_msgs::msg::Lateral::operator !=(
        const Lateral& x) const
{
    return !(*this == x);
}

size_t autoware_control_msgs::msg::Lateral::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Lateral_max_cdr_typesize;
}

size_t autoware_control_msgs::msg::Lateral::getCdrSerializedSize(
        const autoware_control_msgs::msg::Lateral& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.control_time(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void autoware_control_msgs::msg::Lateral::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_control_time;
    scdr << m_steering_tire_angle;
    scdr << m_steering_tire_rotation_rate;
    scdr << m_is_defined_steering_tire_rotation_rate;

}

void autoware_control_msgs::msg::Lateral::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_control_time;
    dcdr >> m_steering_tire_angle;
    dcdr >> m_steering_tire_rotation_rate;
    dcdr >> m_is_defined_steering_tire_rotation_rate;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_control_msgs::msg::Lateral::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_control_msgs::msg::Lateral::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Lateral::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Lateral::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function copies the value in member control_time
 * @param _control_time New value to be copied in member control_time
 */
void autoware_control_msgs::msg::Lateral::control_time(
        const builtin_interfaces::msg::Time& _control_time)
{
    m_control_time = _control_time;
}

/*!
 * @brief This function moves the value in member control_time
 * @param _control_time New value to be moved in member control_time
 */
void autoware_control_msgs::msg::Lateral::control_time(
        builtin_interfaces::msg::Time&& _control_time)
{
    m_control_time = std::move(_control_time);
}

/*!
 * @brief This function returns a constant reference to member control_time
 * @return Constant reference to member control_time
 */
const builtin_interfaces::msg::Time& autoware_control_msgs::msg::Lateral::control_time() const
{
    return m_control_time;
}

/*!
 * @brief This function returns a reference to member control_time
 * @return Reference to member control_time
 */
builtin_interfaces::msg::Time& autoware_control_msgs::msg::Lateral::control_time()
{
    return m_control_time;
}
/*!
 * @brief This function sets a value in member steering_tire_angle
 * @param _steering_tire_angle New value for member steering_tire_angle
 */
void autoware_control_msgs::msg::Lateral::steering_tire_angle(
        float _steering_tire_angle)
{
    m_steering_tire_angle = _steering_tire_angle;
}

/*!
 * @brief This function returns the value of member steering_tire_angle
 * @return Value of member steering_tire_angle
 */
float autoware_control_msgs::msg::Lateral::steering_tire_angle() const
{
    return m_steering_tire_angle;
}

/*!
 * @brief This function returns a reference to member steering_tire_angle
 * @return Reference to member steering_tire_angle
 */
float& autoware_control_msgs::msg::Lateral::steering_tire_angle()
{
    return m_steering_tire_angle;
}

/*!
 * @brief This function sets a value in member steering_tire_rotation_rate
 * @param _steering_tire_rotation_rate New value for member steering_tire_rotation_rate
 */
void autoware_control_msgs::msg::Lateral::steering_tire_rotation_rate(
        float _steering_tire_rotation_rate)
{
    m_steering_tire_rotation_rate = _steering_tire_rotation_rate;
}

/*!
 * @brief This function returns the value of member steering_tire_rotation_rate
 * @return Value of member steering_tire_rotation_rate
 */
float autoware_control_msgs::msg::Lateral::steering_tire_rotation_rate() const
{
    return m_steering_tire_rotation_rate;
}

/*!
 * @brief This function returns a reference to member steering_tire_rotation_rate
 * @return Reference to member steering_tire_rotation_rate
 */
float& autoware_control_msgs::msg::Lateral::steering_tire_rotation_rate()
{
    return m_steering_tire_rotation_rate;
}

/*!
 * @brief This function sets a value in member is_defined_steering_tire_rotation_rate
 * @param _is_defined_steering_tire_rotation_rate New value for member is_defined_steering_tire_rotation_rate
 */
void autoware_control_msgs::msg::Lateral::is_defined_steering_tire_rotation_rate(
        bool _is_defined_steering_tire_rotation_rate)
{
    m_is_defined_steering_tire_rotation_rate = _is_defined_steering_tire_rotation_rate;
}

/*!
 * @brief This function returns the value of member is_defined_steering_tire_rotation_rate
 * @return Value of member is_defined_steering_tire_rotation_rate
 */
bool autoware_control_msgs::msg::Lateral::is_defined_steering_tire_rotation_rate() const
{
    return m_is_defined_steering_tire_rotation_rate;
}

/*!
 * @brief This function returns a reference to member is_defined_steering_tire_rotation_rate
 * @return Reference to member is_defined_steering_tire_rotation_rate
 */
bool& autoware_control_msgs::msg::Lateral::is_defined_steering_tire_rotation_rate()
{
    return m_is_defined_steering_tire_rotation_rate;
}



size_t autoware_control_msgs::msg::Lateral::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_control_msgs_msg_Lateral_max_key_cdr_typesize;
}

bool autoware_control_msgs::msg::Lateral::isKeyDefined()
{
    return false;
}

void autoware_control_msgs::msg::Lateral::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



