// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SteeringReport.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_STEERINGREPORT_H_
#define _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_STEERINGREPORT_H_

#include "Time.h"

#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(STEERINGREPORT_SOURCE)
#define STEERINGREPORT_DllAPI __declspec( dllexport )
#else
#define STEERINGREPORT_DllAPI __declspec( dllimport )
#endif // STEERINGREPORT_SOURCE
#else
#define STEERINGREPORT_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define STEERINGREPORT_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace autoware_vehicle_msgs {
    namespace msg {
        /*!
         * @brief This class represents the structure SteeringReport defined by the user in the IDL file.
         * @ingroup SteeringReport
         */
        class SteeringReport
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport SteeringReport();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~SteeringReport();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object autoware_vehicle_msgs::msg::SteeringReport that will be copied.
             */
            eProsima_user_DllExport SteeringReport(
                    const SteeringReport& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object autoware_vehicle_msgs::msg::SteeringReport that will be copied.
             */
            eProsima_user_DllExport SteeringReport(
                    SteeringReport&& x) noexcept;

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object autoware_vehicle_msgs::msg::SteeringReport that will be copied.
             */
            eProsima_user_DllExport SteeringReport& operator =(
                    const SteeringReport& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object autoware_vehicle_msgs::msg::SteeringReport that will be copied.
             */
            eProsima_user_DllExport SteeringReport& operator =(
                    SteeringReport&& x) noexcept;

            /*!
             * @brief Comparison operator.
             * @param x autoware_vehicle_msgs::msg::SteeringReport object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const SteeringReport& x) const;

            /*!
             * @brief Comparison operator.
             * @param x autoware_vehicle_msgs::msg::SteeringReport object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const SteeringReport& x) const;

            /*!
             * @brief This function copies the value in member stamp
             * @param _stamp New value to be copied in member stamp
             */
            eProsima_user_DllExport void stamp(
                    const builtin_interfaces::msg::Time& _stamp);

            /*!
             * @brief This function moves the value in member stamp
             * @param _stamp New value to be moved in member stamp
             */
            eProsima_user_DllExport void stamp(
                    builtin_interfaces::msg::Time&& _stamp);

            /*!
             * @brief This function returns a constant reference to member stamp
             * @return Constant reference to member stamp
             */
            eProsima_user_DllExport const builtin_interfaces::msg::Time& stamp() const;

            /*!
             * @brief This function returns a reference to member stamp
             * @return Reference to member stamp
             */
            eProsima_user_DllExport builtin_interfaces::msg::Time& stamp();
            /*!
             * @brief This function sets a value in member steering_tire_angle
             * @param _steering_tire_angle New value for member steering_tire_angle
             */
            eProsima_user_DllExport void steering_tire_angle(
                    float _steering_tire_angle);

            /*!
             * @brief This function returns the value of member steering_tire_angle
             * @return Value of member steering_tire_angle
             */
            eProsima_user_DllExport float steering_tire_angle() const;

            /*!
             * @brief This function returns a reference to member steering_tire_angle
             * @return Reference to member steering_tire_angle
             */
            eProsima_user_DllExport float& steering_tire_angle();


            /*!
            * @brief This function returns the maximum serialized size of an object
            * depending on the buffer alignment.
            * @param current_alignment Buffer alignment.
            * @return Maximum serialized size.
            */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const autoware_vehicle_msgs::msg::SteeringReport& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            builtin_interfaces::msg::Time m_stamp;
            float m_steering_tire_angle;

        };
    } // namespace msg
} // namespace autoware_vehicle_msgs

#endif // _FAST_DDS_GENERATED_AUTOWARE_VEHICLE_MSGS_MSG_STEERINGREPORT_H_

