// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SteeringReport.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "SteeringReport.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define autoware_vehicle_msgs_msg_SteeringReport_max_cdr_typesize 12ULL;
#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define autoware_vehicle_msgs_msg_SteeringReport_max_key_cdr_typesize 0ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;

autoware_vehicle_msgs::msg::SteeringReport::SteeringReport()
{
    // builtin_interfaces::msg::Time m_stamp

    // float m_steering_tire_angle
    m_steering_tire_angle = 0.0;

}

autoware_vehicle_msgs::msg::SteeringReport::~SteeringReport()
{


}

autoware_vehicle_msgs::msg::SteeringReport::SteeringReport(
        const SteeringReport& x)
{
    m_stamp = x.m_stamp;
    m_steering_tire_angle = x.m_steering_tire_angle;
}

autoware_vehicle_msgs::msg::SteeringReport::SteeringReport(
        SteeringReport&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_steering_tire_angle = x.m_steering_tire_angle;
}

autoware_vehicle_msgs::msg::SteeringReport& autoware_vehicle_msgs::msg::SteeringReport::operator =(
        const SteeringReport& x)
{

    m_stamp = x.m_stamp;
    m_steering_tire_angle = x.m_steering_tire_angle;

    return *this;
}

autoware_vehicle_msgs::msg::SteeringReport& autoware_vehicle_msgs::msg::SteeringReport::operator =(
        SteeringReport&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_steering_tire_angle = x.m_steering_tire_angle;

    return *this;
}

bool autoware_vehicle_msgs::msg::SteeringReport::operator ==(
        const SteeringReport& x) const
{

    return (m_stamp == x.m_stamp && m_steering_tire_angle == x.m_steering_tire_angle);
}

bool autoware_vehicle_msgs::msg::SteeringReport::operator !=(
        const SteeringReport& x) const
{
    return !(*this == x);
}

size_t autoware_vehicle_msgs::msg::SteeringReport::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_SteeringReport_max_cdr_typesize;
}

size_t autoware_vehicle_msgs::msg::SteeringReport::getCdrSerializedSize(
        const autoware_vehicle_msgs::msg::SteeringReport& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void autoware_vehicle_msgs::msg::SteeringReport::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_steering_tire_angle;

}

void autoware_vehicle_msgs::msg::SteeringReport::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_steering_tire_angle;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void autoware_vehicle_msgs::msg::SteeringReport::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void autoware_vehicle_msgs::msg::SteeringReport::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::SteeringReport::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& autoware_vehicle_msgs::msg::SteeringReport::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function sets a value in member steering_tire_angle
 * @param _steering_tire_angle New value for member steering_tire_angle
 */
void autoware_vehicle_msgs::msg::SteeringReport::steering_tire_angle(
        float _steering_tire_angle)
{
    m_steering_tire_angle = _steering_tire_angle;
}

/*!
 * @brief This function returns the value of member steering_tire_angle
 * @return Value of member steering_tire_angle
 */
float autoware_vehicle_msgs::msg::SteeringReport::steering_tire_angle() const
{
    return m_steering_tire_angle;
}

/*!
 * @brief This function returns a reference to member steering_tire_angle
 * @return Reference to member steering_tire_angle
 */
float& autoware_vehicle_msgs::msg::SteeringReport::steering_tire_angle()
{
    return m_steering_tire_angle;
}



size_t autoware_vehicle_msgs::msg::SteeringReport::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return autoware_vehicle_msgs_msg_SteeringReport_max_key_cdr_typesize;
}

bool autoware_vehicle_msgs::msg::SteeringReport::isKeyDefined()
{
    return false;
}

void autoware_vehicle_msgs::msg::SteeringReport::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



