// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VehicleEmergencyStamped.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VehicleEmergencyStamped.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define tier4_vehicle_msgs_msg_VehicleEmergencyStamped_max_cdr_typesize 9ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define tier4_vehicle_msgs_msg_VehicleEmergencyStamped_max_key_cdr_typesize 0ULL;

tier4_vehicle_msgs::msg::VehicleEmergencyStamped::VehicleEmergencyStamped()
{
    // builtin_interfaces::msg::Time m_stamp

    // boolean m_emergency
    m_emergency = false;

}

tier4_vehicle_msgs::msg::VehicleEmergencyStamped::~VehicleEmergencyStamped()
{


}

tier4_vehicle_msgs::msg::VehicleEmergencyStamped::VehicleEmergencyStamped(
        const VehicleEmergencyStamped& x)
{
    m_stamp = x.m_stamp;
    m_emergency = x.m_emergency;
}

tier4_vehicle_msgs::msg::VehicleEmergencyStamped::VehicleEmergencyStamped(
        VehicleEmergencyStamped&& x) noexcept 
{
    m_stamp = std::move(x.m_stamp);
    m_emergency = x.m_emergency;
}

tier4_vehicle_msgs::msg::VehicleEmergencyStamped& tier4_vehicle_msgs::msg::VehicleEmergencyStamped::operator =(
        const VehicleEmergencyStamped& x)
{

    m_stamp = x.m_stamp;
    m_emergency = x.m_emergency;

    return *this;
}

tier4_vehicle_msgs::msg::VehicleEmergencyStamped& tier4_vehicle_msgs::msg::VehicleEmergencyStamped::operator =(
        VehicleEmergencyStamped&& x) noexcept
{

    m_stamp = std::move(x.m_stamp);
    m_emergency = x.m_emergency;

    return *this;
}

bool tier4_vehicle_msgs::msg::VehicleEmergencyStamped::operator ==(
        const VehicleEmergencyStamped& x) const
{

    return (m_stamp == x.m_stamp && m_emergency == x.m_emergency);
}

bool tier4_vehicle_msgs::msg::VehicleEmergencyStamped::operator !=(
        const VehicleEmergencyStamped& x) const
{
    return !(*this == x);
}

size_t tier4_vehicle_msgs::msg::VehicleEmergencyStamped::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return tier4_vehicle_msgs_msg_VehicleEmergencyStamped_max_cdr_typesize;
}

size_t tier4_vehicle_msgs::msg::VehicleEmergencyStamped::getCdrSerializedSize(
        const tier4_vehicle_msgs::msg::VehicleEmergencyStamped& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += builtin_interfaces::msg::Time::getCdrSerializedSize(data.stamp(), current_alignment);
    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_stamp;
    scdr << m_emergency;

}

void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_stamp;
    dcdr >> m_emergency;
}

/*!
 * @brief This function copies the value in member stamp
 * @param _stamp New value to be copied in member stamp
 */
void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::stamp(
        const builtin_interfaces::msg::Time& _stamp)
{
    m_stamp = _stamp;
}

/*!
 * @brief This function moves the value in member stamp
 * @param _stamp New value to be moved in member stamp
 */
void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::stamp(
        builtin_interfaces::msg::Time&& _stamp)
{
    m_stamp = std::move(_stamp);
}

/*!
 * @brief This function returns a constant reference to member stamp
 * @return Constant reference to member stamp
 */
const builtin_interfaces::msg::Time& tier4_vehicle_msgs::msg::VehicleEmergencyStamped::stamp() const
{
    return m_stamp;
}

/*!
 * @brief This function returns a reference to member stamp
 * @return Reference to member stamp
 */
builtin_interfaces::msg::Time& tier4_vehicle_msgs::msg::VehicleEmergencyStamped::stamp()
{
    return m_stamp;
}
/*!
 * @brief This function sets a value in member emergency
 * @param _emergency New value for member emergency
 */
void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::emergency(
        bool _emergency)
{
    m_emergency = _emergency;
}

/*!
 * @brief This function returns the value of member emergency
 * @return Value of member emergency
 */
bool tier4_vehicle_msgs::msg::VehicleEmergencyStamped::emergency() const
{
    return m_emergency;
}

/*!
 * @brief This function returns a reference to member emergency
 * @return Reference to member emergency
 */
bool& tier4_vehicle_msgs::msg::VehicleEmergencyStamped::emergency()
{
    return m_emergency;
}



size_t tier4_vehicle_msgs::msg::VehicleEmergencyStamped::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return tier4_vehicle_msgs_msg_VehicleEmergencyStamped_max_key_cdr_typesize;
}

bool tier4_vehicle_msgs::msg::VehicleEmergencyStamped::isKeyDefined()
{
    return false;
}

void tier4_vehicle_msgs::msg::VehicleEmergencyStamped::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}



