// autoware_vehicle_msgs/msg/GearCommand.idl
// Canonical IDL definition for autoware_vehicle_msgs::msg::GearCommand

#include "builtin_interfaces/msg/Time.idl"

module autoware_vehicle_msgs {
  module msg {
    struct GearCommand {
      builtin_interfaces::msg::Time stamp;
      octet command;
    };
  };
};
