// autoware_vehicle_msgs/msg/GearReport.idl
// Canonical IDL definition for autoware_vehicle_msgs::msg::GearReport

#include "builtin_interfaces/msg/Time.idl"

module autoware_vehicle_msgs {
  module msg {
    struct GearReport {
      builtin_interfaces::msg::Time stamp;
      octet report;
    };
  };
};
