// autoware_vehicle_msgs/msg/HazardLightsCommand.idl
// Canonical IDL definition for autoware_vehicle_msgs::msg::HazardLightsCommand

#include "builtin_interfaces/msg/Time.idl"

module autoware_vehicle_msgs {
  module msg {
    struct HazardLightsCommand {
      builtin_interfaces::msg::Time stamp;
      octet command;
    };
  };
};
