using System;
using System.IO;
using UnrealBuildTool;

public class CarlaRGL : ModuleRules
{
    public CarlaRGL(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
        bEnableExceptions = true;
        bUseRTTI = true;

        PrivateDependencyModuleNames.AddRange(new string[]
        {
            "Core",
            "CoreUObject",
            "Engine",
            "RenderCore",
            "RHI",
            "PhysicsCore",
            "Chaos",
            "Carla"
        });

        // CarlaRGL plugin root (Plugins/CarlaRGL/)
        string PluginDirectory = Path.GetFullPath(Path.Combine(ModuleDirectory, "..", ".."));

        // .def files are generated by CMake into Build/Unreal/ and symlinked to Carla plugin.
        // Since we're a separate plugin, read from the Carla plugin's symlinks.
        // PluginDirectory = .../Plugins/CarlaRGL/
        // CarlaPluginDir  = .../Plugins/Carla/
        string CarlaPluginDir = Path.GetFullPath(Path.Combine(PluginDirectory, "..", "Carla"));
        string DefsPath = Path.Combine(CarlaPluginDir, "Definitions.def");
        bool EnableRGL = false;

        if (File.Exists(DefsPath))
        {
            foreach (var Def in File.ReadAllText(DefsPath).Split(';'))
            {
                if (Def.Trim() == "WITH_RGL")
                {
                    EnableRGL = true;
                    break;
                }
            }
        }

        if (EnableRGL)
        {
            PrivateDefinitions.Add("WITH_RGL");

            // libRobotecGPULidar.so is in this plugin's Binaries/
            string BinLinux = Path.Combine(PluginDirectory, "Binaries", "Linux");
            string RglSo = Path.Combine(BinLinux, "libRobotecGPULidar.so");
            if (File.Exists(RglSo))
            {
                // No link-time dependency - RGLDynLoader handles dlopen at runtime.
                // Keep RuntimeDependencies for UE packaging.
                RuntimeDependencies.Add(RglSo);
                Console.WriteLine("CarlaRGL: libRobotecGPULidar.so found (will be loaded at runtime via dlopen).");
            }
            else
            {
                Console.WriteLine("CarlaRGL WARNING: libRobotecGPULidar.so not found at " + RglSo);
            }

            // Include all .so files in Binaries/Linux/ for packaging (ROS2 standalone libs etc.)
            foreach (var SoFile in Directory.GetFiles(BinLinux, "*.so*"))
            {
                string FileName = System.IO.Path.GetFileName(SoFile);
                if (FileName != "libRobotecGPULidar.so" && !FileName.StartsWith("libUnrealEditor-"))
                {
                    RuntimeDependencies.Add(SoFile);
                }
            }

            // RGL include paths from Includes.def (filter for RobotecGPULidar entries)
            string IncsPath = Path.Combine(CarlaPluginDir, "Includes.def");
            if (File.Exists(IncsPath))
            {
                foreach (var Inc in File.ReadAllText(IncsPath).Split(';'))
                {
                    var t = Inc.Trim();
                    if (t.Length > 0 && t.Contains("RobotecGPULidar"))
                    {
                        PrivateIncludePaths.Add(t);
                    }
                }
            }
        }
    }
}
