/* AUTO-GENERATED by scripts/generate_cyclonedds_types.sh via idlc. Do not edit directly. */
/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/dds/cyclonedds/types/PoseStamped.h
  Source: /mnt/dsk0/wk0/CARLA/T4ForkWithCycloneDDS/CarlaUE5/LibCarla/source/carla/ros2/types/geometry_msgs/msg/PoseStamped.idl
  Cyclone DDS: V0.10.5

*****************************************************************/
#ifndef DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSESTAMPED_H
#define DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSESTAMPED_H

#include "Header.h"

#include "Pose.h"

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct geometry_msgs_msg_PoseStamped
{
  struct std_msgs_msg_Header header;
  struct geometry_msgs_msg_Pose pose;
} geometry_msgs_msg_PoseStamped;

extern const dds_topic_descriptor_t geometry_msgs_msg_PoseStamped_desc;

#define geometry_msgs_msg_PoseStamped__alloc() \
((geometry_msgs_msg_PoseStamped*) dds_alloc (sizeof (geometry_msgs_msg_PoseStamped)));

#define geometry_msgs_msg_PoseStamped_free(d,o) \
dds_sample_free ((d), &geometry_msgs_msg_PoseStamped_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC__MNT_DSK0_WK0_CARLA_T4FORKWITHCYCLONEDDS_CARLAUE5_LIBCARLA_SOURCE_CARLA_ROS2_DDS_CYCLONEDDS_TYPES_POSESTAMPED_H */
