#!/bin/bash
# generate_cyclonedds_types.sh
# Generate CycloneDDS C type files from IDL definitions
#
# Prerequisites: idlc must be in PATH (installed with CycloneDDS)
#
# Usage: ./generate_cyclonedds_types.sh [output_dir]
#
# If output_dir is not specified, defaults to ../cyclonedds/types
# relative to the script location.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IDL_DIR="${SCRIPT_DIR}/../types"
OUTPUT_DIR="${1:-${SCRIPT_DIR}/../cyclonedds/types}"

# Verify idlc is available
if ! command -v idlc &> /dev/null; then
    echo "Error: idlc not found in PATH." >&2
    echo "Install CycloneDDS and ensure idlc is in your PATH." >&2
    echo "  e.g., export PATH=\$CYCLONEDDS_INSTALL/bin:\$PATH" >&2
    exit 1
fi

# Verify IDL directory exists
if [ ! -d "$IDL_DIR" ]; then
    echo "Error: IDL directory not found: $IDL_DIR" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo "Generating CycloneDDS types from IDL files..."
echo "  IDL directory:    $IDL_DIR"
echo "  Output directory: $OUTPUT_DIR"
echo ""

# Count IDL files
IDL_COUNT=0
FAIL_COUNT=0

# Find all .idl files and generate C types
# Sort to ensure deterministic ordering
find "$IDL_DIR" -name "*.idl" | sort | while read -r idl_file; do
    rel_path="${idl_file#$IDL_DIR/}"
    echo "  Processing: $rel_path"

    if idlc -f case-sensitive -l c "$idl_file" -o "$OUTPUT_DIR" -I "$IDL_DIR"; then
        IDL_COUNT=$((IDL_COUNT + 1))
    else
        echo "    WARNING: Failed to process $rel_path" >&2
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
done

echo ""

# Post-process: flatten package-relative includes
# idlc generates #include "std_msgs/msg/Header.h" but files are in a flat directory
echo "Post-processing: flattening include paths..."
sed -i 's|#include "\([a-z_]*/msg/\)\([A-Za-z0-9_]*\.h\)"|#include "\2"|g' "$OUTPUT_DIR"/*.h 2>/dev/null || true

# Post-process: convert m_typename to ROS2 DDS wire format
# idlc generates .m_typename = "pkg::msg::Type" but ROS2 expects "pkg::msg::dds_::Type_"
echo "Post-processing: converting m_typename to ROS2 DDS wire format..."
sed -i 's|\.m_typename = "\([^"]*\)::msg::\([^"]*\)"|.m_typename = "\1::msg::dds_::\2_"|g' "$OUTPUT_DIR"/*.c 2>/dev/null || true

# Post-process: add "do not edit" header to all generated files
echo "Post-processing: adding generation header comments..."
for f in "$OUTPUT_DIR"/*.h "$OUTPUT_DIR"/*.c; do
  [ -f "$f" ] || continue
  # Skip if header already present
  if ! grep -q 'AUTO-GENERATED by scripts/generate_cyclonedds_types.sh' "$f"; then
    sed -i '1i\/* AUTO-GENERATED by scripts\/generate_cyclonedds_types.sh via idlc. Do not edit directly. */' "$f"
  fi
done

echo "Done. Generated types in: $OUTPUT_DIR"

if [ "$FAIL_COUNT" -gt 0 ]; then
    echo "WARNING: $FAIL_COUNT file(s) failed to process." >&2
    exit 1
fi
