// rosgraph_msgs/msg/Clock.idl
// Canonical IDL definition for rosgraph_msgs::msg::Clock

#include "builtin_interfaces/msg/Time.idl"

module rosgraph_msgs {
  module msg {
    struct Clock {
      builtin_interfaces::msg::Time clock;
    };
  };
};
