// *** AUTO-GENERATED by tools/generate_cyclonedds_publishers.py ***
// Do not edit this file directly. Modify the script or the FastDDS
// source and regenerate.

#include "CarlaSSCameraPublisher.h"

#include <string>
#include <cstring>
#include <vector>

#include "carla/ros2/dds/DDSPublisherImpl.h"
#include "Image.h"
#include "CameraInfo.h"
#include "RegionOfInterest.h"
#include "Header.h"
#include "Time.h"
#include "CycloneCameraInfoHelper.h"

namespace carla {
namespace ros2 {

  struct CarlaSSCameraPublisherImpl {
    std::unique_ptr<DDSPublisherImpl> _dds_image;
    std::unique_ptr<DDSPublisherImpl> _dds_info;
    sensor_msgs_msg_Image _image {};
    sensor_msgs_msg_CameraInfo _info {};
    bool _info_init {false};
    std::string _frame_id_store;
    std::string _encoding_store;
    std::vector<uint8_t> _data_store;
    std::vector<double> _d_store;
    std::string _distortion_model_store;
  };

  bool CarlaSSCameraPublisher::HasBeenInitialized() const {
    return _impl->_info_init;
  }

  void CarlaSSCameraPublisher::InitInfoData(uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, float fov, bool do_rectify) {
    cyclone_helpers::InitCameraInfo(_impl->_info, height, width, fov, _impl->_d_store, _impl->_distortion_model_store);
    SetInfoRegionOfInterest(x_offset, y_offset, height, width, do_rectify);
    _impl->_info_init = true;
  }

  bool CarlaSSCameraPublisher::Init(const TopicConfig& config) {
    return InitImage(config) && InitInfo(config);
  }

  bool CarlaSSCameraPublisher::InitImage(const TopicConfig& config) {
    _impl->_dds_image = CreateDDSPublisher("sensor_msgs::msg::Image");
    if (!_impl->_dds_image) return false;

    const std::string publisher_type {"/image"};
    const std::string base { "rt/carla/" };
    std::string topic_name = base;
    if (!_parent.empty())
      topic_name += _parent + "/";
    topic_name += _name;
    topic_name += publisher_type;
    if (const auto custom_topic_name = ValidTopicName(publisher_type)) {
      topic_name = custom_topic_name.value();
    }

    if (!_impl->_dds_image->Init(config, _name, topic_name, /*use_preallocated_realloc=*/true)) {
      return false;
    }
    _frame_id = _name;
    return true;
  }

  bool CarlaSSCameraPublisher::InitInfo(const TopicConfig& config) {
    _impl->_dds_info = CreateDDSPublisher("sensor_msgs::msg::CameraInfo");
    if (!_impl->_dds_info) return false;

    const std::string publisher_type {"/camera_info"};
    const std::string base { "rt/carla/" };
    std::string topic_name = base;
    if (!_parent.empty())
      topic_name += _parent + "/";
    topic_name += _name;
    topic_name += publisher_type;
    if (const auto custom_topic_name = ValidTopicName(publisher_type)) {
      topic_name = custom_topic_name.value();
    }

    if (!_impl->_dds_info->Init(config, _name, topic_name, /*use_preallocated_realloc=*/false)) {
      return false;
    }
    _frame_id = _name;
    return true;
  }

  bool CarlaSSCameraPublisher::Publish() {
    return PublishImage() && PublishInfo();
  }

  bool CarlaSSCameraPublisher::PublishImage() {
    return _impl->_dds_image->Write(&_impl->_image);
  }

  bool CarlaSSCameraPublisher::PublishInfo() {
    return _impl->_dds_info->Write(&_impl->_info);
  }

  void CarlaSSCameraPublisher::SetImageData(int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, const uint8_t* data) {
    std::vector<uint8_t> vector_data;
    const size_t size = height * width * 4;
    vector_data.resize(size);
    std::memcpy(&vector_data[0], &data[0], size);
    SetData(seconds, nanoseconds, height, width, std::move(vector_data));
  }

  void CarlaSSCameraPublisher::SetInfoRegionOfInterest(uint32_t x_offset, uint32_t y_offset, uint32_t height, uint32_t width, bool do_rectify) {
    sensor_msgs_msg_RegionOfInterest roi;
    roi.x_offset = x_offset;
    roi.y_offset = y_offset;
    roi.height = height;
    roi.width = width;
    roi.do_rectify = do_rectify;
    _impl->_info.roi = roi;
  }

  void CarlaSSCameraPublisher::SetData(int32_t seconds, uint32_t nanoseconds, size_t height, size_t width, std::vector<uint8_t>&& data) {
    builtin_interfaces_msg_Time time;
    time.sec = seconds;
    time.nanosec = nanoseconds;

    _impl->_frame_id_store = _frame_id;
    std_msgs_msg_Header header;
    header.stamp = time;
    header.frame_id = const_cast<char*>(_impl->_frame_id_store.c_str());

    _impl->_image.header = header;
    _impl->_image.width = width;
    _impl->_image.height = height;
    _impl->_encoding_store = "bgra8";
    _impl->_image.encoding = const_cast<char*>(_impl->_encoding_store.c_str());
    _impl->_image.is_bigendian = 0;
    _impl->_image.step = _impl->_image.width * sizeof(uint8_t) * 4;
    _impl->_data_store = std::move(data);
    _impl->_image.data._buffer = _impl->_data_store.data();
    _impl->_image.data._length = static_cast<uint32_t>(_impl->_data_store.size());
    _impl->_image.data._maximum = static_cast<uint32_t>(_impl->_data_store.size());
    _impl->_image.data._release = false;
  }

  void CarlaSSCameraPublisher::SetCameraInfoData(int32_t seconds, uint32_t nanoseconds) {
    builtin_interfaces_msg_Time time;
    time.sec = seconds;
    time.nanosec = nanoseconds;

    _impl->_frame_id_store = _frame_id;
    std_msgs_msg_Header header;
    header.stamp = time;
    header.frame_id = const_cast<char*>(_impl->_frame_id_store.c_str());
    _impl->_info.header = header;
  }

  CarlaSSCameraPublisher::CarlaSSCameraPublisher(const char* ros_name, const char* parent, const char* ros_topic_name) :
  _impl(std::make_shared<CarlaSSCameraPublisherImpl>()) {
    _name = ros_name;
    _parent = parent;
    _topic_name = ros_topic_name;
  }

  CarlaSSCameraPublisher::~CarlaSSCameraPublisher() = default;
  CarlaSSCameraPublisher::CarlaSSCameraPublisher(const CarlaSSCameraPublisher&) = default;
  CarlaSSCameraPublisher& CarlaSSCameraPublisher::operator=(const CarlaSSCameraPublisher&) = default;
  CarlaSSCameraPublisher::CarlaSSCameraPublisher(CarlaSSCameraPublisher&&) = default;
  CarlaSSCameraPublisher& CarlaSSCameraPublisher::operator=(CarlaSSCameraPublisher&&) = default;
}
}
